/**
Copyright (c) 2012-2020, Brice Videau <bvideau@anl.gov>
Copyright (c) 2012-2020, Vincent Danjean <Vincent.Danjean@ens-lyon.org>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Do not edit this file. It is automatically generated.

*/
#define CL_TARGET_OPENCL_VERSION 300
#include <CL/opencl.h>
#include <CL/cl.h>
#include <CL/cl_gl.h>
#include <CL/cl_egl.h>
#include <CL/cl_ext.h>


struct _cl_icd_dispatch;
struct _cl_platform_id { struct _cl_icd_dispatch *dispatch; };

struct _cl_icd_dispatch {
  void(*known0)(void);
  void(*known1)(void);
  void(*known2)(void);
  void(*known3)(void);
  void(*known4)(void);
  void(*known5)(void);
  void(*known6)(void);
  void(*known7)(void);
  void(*known8)(void);
  void(*known9)(void);
  void(*known10)(void);
  void(*known11)(void);
  void(*known12)(void);
  void(*known13)(void);
  void(*known14)(void);
  void(*known15)(void);
  void(*known16)(void);
  void(*known17)(void);
  void(*known18)(void);
  void(*known19)(void);
  void(*known20)(void);
  void(*known21)(void);
  void(*known22)(void);
  void(*known23)(void);
  void(*known24)(void);
  void(*known25)(void);
  void(*known26)(void);
  void(*known27)(void);
  void(*known28)(void);
  void(*known29)(void);
  void(*known30)(void);
  void(*known31)(void);
  void(*known32)(void);
  void(*known33)(void);
  void(*known34)(void);
  void(*known35)(void);
  void(*known36)(void);
  void(*known37)(void);
  void(*known38)(void);
  void(*known39)(void);
  void(*known40)(void);
  void(*known41)(void);
  void(*known42)(void);
  void(*known43)(void);
  void(*known44)(void);
  void(*known45)(void);
  void(*known46)(void);
  void(*known47)(void);
  void(*known48)(void);
  void(*known49)(void);
  void(*known50)(void);
  void(*known51)(void);
  void(*known52)(void);
  void(*known53)(void);
  void(*known54)(void);
  void(*known55)(void);
  void(*known56)(void);
  void(*known57)(void);
  void(*known58)(void);
  void(*known59)(void);
  void(*known60)(void);
  void(*known61)(void);
  void(*known62)(void);
  void(*known63)(void);
  void(*known64)(void);
  void(*known65)(void);
  void(*known66)(void);
  void(*known67)(void);
  void(*known68)(void);
  void(*known69)(void);
  void(*known70)(void);
  void(*known71)(void);
  void(*known72)(void);
  void(*known73)(void);
  void(*known74)(void);
  void(*unknown75)(void);
  void(*unknown76)(void);
  void(*unknown77)(void);
  void(*unknown78)(void);
  void(*unknown79)(void);
  void(*unknown80)(void);
  void(*known81)(void);
  void(*known82)(void);
  void(*known83)(void);
  void(*known84)(void);
  void(*known85)(void);
  void(*known86)(void);
  void(*known87)(void);
  void(*known88)(void);
  void(*known89)(void);
  void(*known90)(void);
  void(*known91)(void);
  void(*known92)(void);
  void(*known93)(void);
  void(*known94)(void);
  void(*known95)(void);
  void(*known96)(void);
  void(*known97)(void);
  void(*known98)(void);
  void(*known99)(void);
  void(*known100)(void);
  void(*known101)(void);
  void(*known102)(void);
  void(*known103)(void);
  void(*known104)(void);
  void(*known105)(void);
  void(*known106)(void);
  void(*known107)(void);
  void(*known108)(void);
  void(*unknown109)(void);
  void(*unknown110)(void);
  void(*unknown111)(void);
  void(*unknown112)(void);
  void(*unknown113)(void);
  void(*unknown114)(void);
  void(*unknown115)(void);
  void(*unknown116)(void);
  void(*unknown117)(void);
  void(*unknown118)(void);
  void(*known119)(void);
  void(*known120)(void);
  void(*known121)(void);
  void(*known122)(void);
  void(*known123)(void);
  void(*known124)(void);
  void(*known125)(void);
  void(*known126)(void);
  void(*known127)(void);
  void(*known128)(void);
  void(*known129)(void);
  void(*known130)(void);
  void(*known131)(void);
  void(*known132)(void);
  void(*known133)(void);
  void(*known134)(void);
  void(*known135)(void);
  void(*known136)(void);
  void(*known137)(void);
  void(*known138)(void);
  void(*known139)(void);
  void(*known140)(void);
  void(*known141)(void);
  void(*known142)(void);
  void(*known143)(void);
  void(*known144)(void);
  void(*known145)(void);
  void(*known146)(void);
  void(*known147)(void);
  void(*known148)(void);
  void(*unknown149)(void);
  void(*unknown150)(void);
  void(*unknown151)(void);
  void(*unknown152)(void);
  void(*unknown153)(void);
  void(*unknown154)(void);
  void(*unknown155)(void);
  void(*unknown156)(void);
  void(*unknown157)(void);
  void(*unknown158)(void);
  void(*unknown159)(void);
  void(*unknown160)(void);
  void(*unknown161)(void);
  void(*unknown162)(void);
  void(*unknown163)(void);
  void(*unknown164)(void);
  void(*unknown165)(void);
  void(*unknown166)(void);
  void(*unknown167)(void);
  void(*unknown168)(void);
  void(*unknown169)(void);
  void(*unknown170)(void);
  void(*unknown171)(void);
  void(*unknown172)(void);
  void(*unknown173)(void);
  void(*unknown174)(void);
  void(*unknown175)(void);
  void(*unknown176)(void);
  void(*unknown177)(void);
  void(*unknown178)(void);
  void(*unknown179)(void);
  void(*unknown180)(void);
  void(*unknown181)(void);
  void(*unknown182)(void);
};

#pragma GCC visibility push(hidden)

extern struct _cl_icd_dispatch master_dispatch; 

#if defined(__APPLE__) || defined(__MACOSX)
#define INTclGetPlatformInfo clGetPlatformInfo
#define INTclGetPlatformIDs clGetPlatformIDs
#define INTclGetDeviceIDs clGetDeviceIDs
#else
typeof(clGetPlatformInfo) INTclGetPlatformInfo;
typeof(clGetPlatformIDs) INTclGetPlatformIDs;
typeof(clGetDeviceIDs) INTclGetDeviceIDs;
#endif
#pragma GCC visibility pop

