/**
Copyright (c) 2012-2020, Brice Videau <bvideau@anl.gov>
Copyright (c) 2012-2020, Vincent Danjean <Vincent.Danjean@ens-lyon.org>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Do not edit this file. It is automatically generated.

*/

#include <stdio.h>

#include "libdummy_icd_gen.h"

#include "libdummy_icd.h"

void dummyFunc0(void){ printf("0  : "); fflush(NULL); }
void dummyFunc1(void){ printf("1  : "); fflush(NULL); }
void dummyFunc2(void){ printf("2  : "); fflush(NULL); }
void dummyFunc3(void){ printf("3  : "); fflush(NULL); }
void dummyFunc4(void){ printf("4  : "); fflush(NULL); }
void dummyFunc5(void){ printf("5  : "); fflush(NULL); }
void dummyFunc6(void){ printf("6  : "); fflush(NULL); }
void dummyFunc7(void){ printf("7  : "); fflush(NULL); }
void dummyFunc8(void){ printf("8  : "); fflush(NULL); }
void dummyFunc9(void){ printf("9  : "); fflush(NULL); }
void dummyFunc10(void){ printf("10  : "); fflush(NULL); }
void dummyFunc11(void){ printf("11  : "); fflush(NULL); }
void dummyFunc12(void){ printf("12  : "); fflush(NULL); }
void dummyFunc13(void){ printf("13  : "); fflush(NULL); }
void dummyFunc14(void){ printf("14  : "); fflush(NULL); }
void dummyFunc15(void){ printf("15  : "); fflush(NULL); }
void dummyFunc16(void){ printf("16  : "); fflush(NULL); }
void dummyFunc17(void){ printf("17  : "); fflush(NULL); }
void dummyFunc18(void){ printf("18  : "); fflush(NULL); }
void dummyFunc19(void){ printf("19  : "); fflush(NULL); }
void dummyFunc20(void){ printf("20  : "); fflush(NULL); }
void dummyFunc21(void){ printf("21  : "); fflush(NULL); }
void dummyFunc22(void){ printf("22  : "); fflush(NULL); }
void dummyFunc23(void){ printf("23  : "); fflush(NULL); }
void dummyFunc24(void){ printf("24  : "); fflush(NULL); }
void dummyFunc25(void){ printf("25  : "); fflush(NULL); }
void dummyFunc26(void){ printf("26  : "); fflush(NULL); }
void dummyFunc27(void){ printf("27  : "); fflush(NULL); }
void dummyFunc28(void){ printf("28  : "); fflush(NULL); }
void dummyFunc29(void){ printf("29  : "); fflush(NULL); }
void dummyFunc30(void){ printf("30  : "); fflush(NULL); }
void dummyFunc31(void){ printf("31  : "); fflush(NULL); }
void dummyFunc32(void){ printf("32  : "); fflush(NULL); }
void dummyFunc33(void){ printf("33  : "); fflush(NULL); }
void dummyFunc34(void){ printf("34  : "); fflush(NULL); }
void dummyFunc35(void){ printf("35  : "); fflush(NULL); }
void dummyFunc36(void){ printf("36  : "); fflush(NULL); }
void dummyFunc37(void){ printf("37  : "); fflush(NULL); }
void dummyFunc38(void){ printf("38  : "); fflush(NULL); }
void dummyFunc39(void){ printf("39  : "); fflush(NULL); }
void dummyFunc40(void){ printf("40  : "); fflush(NULL); }
void dummyFunc41(void){ printf("41  : "); fflush(NULL); }
void dummyFunc42(void){ printf("42  : "); fflush(NULL); }
void dummyFunc43(void){ printf("43  : "); fflush(NULL); }
void dummyFunc44(void){ printf("44  : "); fflush(NULL); }
void dummyFunc45(void){ printf("45  : "); fflush(NULL); }
void dummyFunc46(void){ printf("46  : "); fflush(NULL); }
void dummyFunc47(void){ printf("47  : "); fflush(NULL); }
void dummyFunc48(void){ printf("48  : "); fflush(NULL); }
void dummyFunc49(void){ printf("49  : "); fflush(NULL); }
void dummyFunc50(void){ printf("50  : "); fflush(NULL); }
void dummyFunc51(void){ printf("51  : "); fflush(NULL); }
void dummyFunc52(void){ printf("52  : "); fflush(NULL); }
void dummyFunc53(void){ printf("53  : "); fflush(NULL); }
void dummyFunc54(void){ printf("54  : "); fflush(NULL); }
void dummyFunc55(void){ printf("55  : "); fflush(NULL); }
void dummyFunc56(void){ printf("56  : "); fflush(NULL); }
void dummyFunc57(void){ printf("57  : "); fflush(NULL); }
void dummyFunc58(void){ printf("58  : "); fflush(NULL); }
void dummyFunc59(void){ printf("59  : "); fflush(NULL); }
void dummyFunc60(void){ printf("60  : "); fflush(NULL); }
void dummyFunc61(void){ printf("61  : "); fflush(NULL); }
void dummyFunc62(void){ printf("62  : "); fflush(NULL); }
void dummyFunc63(void){ printf("63  : "); fflush(NULL); }
void dummyFunc64(void){ printf("64  : "); fflush(NULL); }
void dummyFunc65(void){ printf("65  : "); fflush(NULL); }
void dummyFunc66(void){ printf("66  : "); fflush(NULL); }
void dummyFunc67(void){ printf("67  : "); fflush(NULL); }
void dummyFunc68(void){ printf("68  : "); fflush(NULL); }
void dummyFunc69(void){ printf("69  : "); fflush(NULL); }
void dummyFunc70(void){ printf("70  : "); fflush(NULL); }
void dummyFunc71(void){ printf("71  : "); fflush(NULL); }
void dummyFunc72(void){ printf("72  : "); fflush(NULL); }
void dummyFunc73(void){ printf("73  : "); fflush(NULL); }
void dummyFunc74(void){ printf("74  : "); fflush(NULL); }
void dummyFunc75(void){ printf("75  : "); fflush(NULL); }
void dummyFunc76(void){ printf("76  : "); fflush(NULL); }
void dummyFunc77(void){ printf("77  : "); fflush(NULL); }
void dummyFunc78(void){ printf("78  : "); fflush(NULL); }
void dummyFunc79(void){ printf("79  : "); fflush(NULL); }
void dummyFunc80(void){ printf("80  : "); fflush(NULL); }
void dummyFunc81(void){ printf("81  : "); fflush(NULL); }
void dummyFunc82(void){ printf("82  : "); fflush(NULL); }
void dummyFunc83(void){ printf("83  : "); fflush(NULL); }
void dummyFunc84(void){ printf("84  : "); fflush(NULL); }
void dummyFunc85(void){ printf("85  : "); fflush(NULL); }
void dummyFunc86(void){ printf("86  : "); fflush(NULL); }
void dummyFunc87(void){ printf("87  : "); fflush(NULL); }
void dummyFunc88(void){ printf("88  : "); fflush(NULL); }
void dummyFunc89(void){ printf("89  : "); fflush(NULL); }
void dummyFunc90(void){ printf("90  : "); fflush(NULL); }
void dummyFunc91(void){ printf("91  : "); fflush(NULL); }
void dummyFunc92(void){ printf("92  : "); fflush(NULL); }
void dummyFunc93(void){ printf("93  : "); fflush(NULL); }
void dummyFunc94(void){ printf("94  : "); fflush(NULL); }
void dummyFunc95(void){ printf("95  : "); fflush(NULL); }
void dummyFunc96(void){ printf("96  : "); fflush(NULL); }
void dummyFunc97(void){ printf("97  : "); fflush(NULL); }
void dummyFunc98(void){ printf("98  : "); fflush(NULL); }
void dummyFunc99(void){ printf("99  : "); fflush(NULL); }
void dummyFunc100(void){ printf("100  : "); fflush(NULL); }
void dummyFunc101(void){ printf("101  : "); fflush(NULL); }
void dummyFunc102(void){ printf("102  : "); fflush(NULL); }
void dummyFunc103(void){ printf("103  : "); fflush(NULL); }
void dummyFunc104(void){ printf("104  : "); fflush(NULL); }
void dummyFunc105(void){ printf("105  : "); fflush(NULL); }
void dummyFunc106(void){ printf("106  : "); fflush(NULL); }
void dummyFunc107(void){ printf("107  : "); fflush(NULL); }
void dummyFunc108(void){ printf("108  : "); fflush(NULL); }
void dummyFunc109(void){ printf("109  : "); fflush(NULL); }
void dummyFunc110(void){ printf("110  : "); fflush(NULL); }
void dummyFunc111(void){ printf("111  : "); fflush(NULL); }
void dummyFunc112(void){ printf("112  : "); fflush(NULL); }
void dummyFunc113(void){ printf("113  : "); fflush(NULL); }
void dummyFunc114(void){ printf("114  : "); fflush(NULL); }
void dummyFunc115(void){ printf("115  : "); fflush(NULL); }
void dummyFunc116(void){ printf("116  : "); fflush(NULL); }
void dummyFunc117(void){ printf("117  : "); fflush(NULL); }
void dummyFunc118(void){ printf("118  : "); fflush(NULL); }
void dummyFunc119(void){ printf("119  : "); fflush(NULL); }
void dummyFunc120(void){ printf("120  : "); fflush(NULL); }
void dummyFunc121(void){ printf("121  : "); fflush(NULL); }
void dummyFunc122(void){ printf("122  : "); fflush(NULL); }
void dummyFunc123(void){ printf("123  : "); fflush(NULL); }
void dummyFunc124(void){ printf("124  : "); fflush(NULL); }
void dummyFunc125(void){ printf("125  : "); fflush(NULL); }
void dummyFunc126(void){ printf("126  : "); fflush(NULL); }
void dummyFunc127(void){ printf("127  : "); fflush(NULL); }
void dummyFunc128(void){ printf("128  : "); fflush(NULL); }
void dummyFunc129(void){ printf("129  : "); fflush(NULL); }
void dummyFunc130(void){ printf("130  : "); fflush(NULL); }
void dummyFunc131(void){ printf("131  : "); fflush(NULL); }
void dummyFunc132(void){ printf("132  : "); fflush(NULL); }
void dummyFunc133(void){ printf("133  : "); fflush(NULL); }
void dummyFunc134(void){ printf("134  : "); fflush(NULL); }
void dummyFunc135(void){ printf("135  : "); fflush(NULL); }
void dummyFunc136(void){ printf("136  : "); fflush(NULL); }
void dummyFunc137(void){ printf("137  : "); fflush(NULL); }
void dummyFunc138(void){ printf("138  : "); fflush(NULL); }
void dummyFunc139(void){ printf("139  : "); fflush(NULL); }
void dummyFunc140(void){ printf("140  : "); fflush(NULL); }
void dummyFunc141(void){ printf("141  : "); fflush(NULL); }
void dummyFunc142(void){ printf("142  : "); fflush(NULL); }
void dummyFunc143(void){ printf("143  : "); fflush(NULL); }
void dummyFunc144(void){ printf("144  : "); fflush(NULL); }
void dummyFunc145(void){ printf("145  : "); fflush(NULL); }
void dummyFunc146(void){ printf("146  : "); fflush(NULL); }
void dummyFunc147(void){ printf("147  : "); fflush(NULL); }
void dummyFunc148(void){ printf("148  : "); fflush(NULL); }
void dummyFunc149(void){ printf("149  : "); fflush(NULL); }
void dummyFunc150(void){ printf("150  : "); fflush(NULL); }
void dummyFunc151(void){ printf("151  : "); fflush(NULL); }
void dummyFunc152(void){ printf("152  : "); fflush(NULL); }
void dummyFunc153(void){ printf("153  : "); fflush(NULL); }
void dummyFunc154(void){ printf("154  : "); fflush(NULL); }
void dummyFunc155(void){ printf("155  : "); fflush(NULL); }
void dummyFunc156(void){ printf("156  : "); fflush(NULL); }
void dummyFunc157(void){ printf("157  : "); fflush(NULL); }
void dummyFunc158(void){ printf("158  : "); fflush(NULL); }
void dummyFunc159(void){ printf("159  : "); fflush(NULL); }
void dummyFunc160(void){ printf("160  : "); fflush(NULL); }
void dummyFunc161(void){ printf("161  : "); fflush(NULL); }
void dummyFunc162(void){ printf("162  : "); fflush(NULL); }
void dummyFunc163(void){ printf("163  : "); fflush(NULL); }
void dummyFunc164(void){ printf("164  : "); fflush(NULL); }
void dummyFunc165(void){ printf("165  : "); fflush(NULL); }
void dummyFunc166(void){ printf("166  : "); fflush(NULL); }
void dummyFunc167(void){ printf("167  : "); fflush(NULL); }
void dummyFunc168(void){ printf("168  : "); fflush(NULL); }
void dummyFunc169(void){ printf("169  : "); fflush(NULL); }
void dummyFunc170(void){ printf("170  : "); fflush(NULL); }
void dummyFunc171(void){ printf("171  : "); fflush(NULL); }
void dummyFunc172(void){ printf("172  : "); fflush(NULL); }
void dummyFunc173(void){ printf("173  : "); fflush(NULL); }
void dummyFunc174(void){ printf("174  : "); fflush(NULL); }
void dummyFunc175(void){ printf("175  : "); fflush(NULL); }
void dummyFunc176(void){ printf("176  : "); fflush(NULL); }
void dummyFunc177(void){ printf("177  : "); fflush(NULL); }
void dummyFunc178(void){ printf("178  : "); fflush(NULL); }
void dummyFunc179(void){ printf("179  : "); fflush(NULL); }
void dummyFunc180(void){ printf("180  : "); fflush(NULL); }
void dummyFunc181(void){ printf("181  : "); fflush(NULL); }
void dummyFunc182(void){ printf("182  : "); fflush(NULL); }

struct _cl_icd_dispatch master_dispatch = {
  (void(*)(void))& INTclGetPlatformIDs,
  (void(*)(void))& INTclGetPlatformInfo,
  (void(*)(void))& INTclGetDeviceIDs,
  (void(*)(void))& dummyFunc3,
  (void(*)(void))& dummyFunc4,
  (void(*)(void))& dummyFunc5,
  (void(*)(void))& dummyFunc6,
  (void(*)(void))& dummyFunc7,
  (void(*)(void))& dummyFunc8,
  (void(*)(void))& dummyFunc9,
  (void(*)(void))& dummyFunc10,
  (void(*)(void))& dummyFunc11,
  (void(*)(void))& dummyFunc12,
  (void(*)(void))& dummyFunc13,
  (void(*)(void))& dummyFunc14,
  (void(*)(void))& dummyFunc15,
  (void(*)(void))& dummyFunc16,
  (void(*)(void))& dummyFunc17,
  (void(*)(void))& dummyFunc18,
  (void(*)(void))& dummyFunc19,
  (void(*)(void))& dummyFunc20,
  (void(*)(void))& dummyFunc21,
  (void(*)(void))& dummyFunc22,
  (void(*)(void))& dummyFunc23,
  (void(*)(void))& dummyFunc24,
  (void(*)(void))& dummyFunc25,
  (void(*)(void))& dummyFunc26,
  (void(*)(void))& dummyFunc27,
  (void(*)(void))& dummyFunc28,
  (void(*)(void))& dummyFunc29,
  (void(*)(void))& dummyFunc30,
  (void(*)(void))& dummyFunc31,
  (void(*)(void))& dummyFunc32,
  (void(*)(void))& dummyFunc33,
  (void(*)(void))& dummyFunc34,
  (void(*)(void))& dummyFunc35,
  (void(*)(void))& dummyFunc36,
  (void(*)(void))& dummyFunc37,
  (void(*)(void))& dummyFunc38,
  (void(*)(void))& dummyFunc39,
  (void(*)(void))& dummyFunc40,
  (void(*)(void))& dummyFunc41,
  (void(*)(void))& dummyFunc42,
  (void(*)(void))& dummyFunc43,
  (void(*)(void))& dummyFunc44,
  (void(*)(void))& dummyFunc45,
  (void(*)(void))& dummyFunc46,
  (void(*)(void))& dummyFunc47,
  (void(*)(void))& dummyFunc48,
  (void(*)(void))& dummyFunc49,
  (void(*)(void))& dummyFunc50,
  (void(*)(void))& dummyFunc51,
  (void(*)(void))& dummyFunc52,
  (void(*)(void))& dummyFunc53,
  (void(*)(void))& dummyFunc54,
  (void(*)(void))& dummyFunc55,
  (void(*)(void))& dummyFunc56,
  (void(*)(void))& dummyFunc57,
  (void(*)(void))& dummyFunc58,
  (void(*)(void))& dummyFunc59,
  (void(*)(void))& dummyFunc60,
  (void(*)(void))& dummyFunc61,
  (void(*)(void))& dummyFunc62,
  (void(*)(void))& dummyFunc63,
  (void(*)(void))& dummyFunc64,
  (void(*)(void))& dummyFunc65,
  (void(*)(void))& dummyFunc66,
  (void(*)(void))& dummyFunc67,
  (void(*)(void))& dummyFunc68,
  (void(*)(void))& dummyFunc69,
  (void(*)(void))& dummyFunc70,
  (void(*)(void))& dummyFunc71,
  (void(*)(void))& dummyFunc72,
  (void(*)(void))& dummyFunc73,
  (void(*)(void))& dummyFunc74,
  (void(*)(void))& dummyFunc75,
  (void(*)(void))& dummyFunc76,
  (void(*)(void))& dummyFunc77,
  (void(*)(void))& dummyFunc78,
  (void(*)(void))& dummyFunc79,
  (void(*)(void))& dummyFunc80,
  (void(*)(void))& dummyFunc81,
  (void(*)(void))& dummyFunc82,
  (void(*)(void))& dummyFunc83,
  (void(*)(void))& dummyFunc84,
  (void(*)(void))& dummyFunc85,
  (void(*)(void))& dummyFunc86,
  (void(*)(void))& dummyFunc87,
  (void(*)(void))& dummyFunc88,
  (void(*)(void))& dummyFunc89,
  (void(*)(void))& dummyFunc90,
  (void(*)(void))& dummyFunc91,
  (void(*)(void))& dummyFunc92,
  (void(*)(void))& dummyFunc93,
  (void(*)(void))& dummyFunc94,
  (void(*)(void))& dummyFunc95,
  (void(*)(void))& dummyFunc96,
  (void(*)(void))& dummyFunc97,
  (void(*)(void))& dummyFunc98,
  (void(*)(void))& dummyFunc99,
  (void(*)(void))& dummyFunc100,
  (void(*)(void))& dummyFunc101,
  (void(*)(void))& dummyFunc102,
  (void(*)(void))& dummyFunc103,
  (void(*)(void))& dummyFunc104,
  (void(*)(void))& dummyFunc105,
  (void(*)(void))& dummyFunc106,
  (void(*)(void))& dummyFunc107,
  (void(*)(void))& dummyFunc108,
  (void(*)(void))& dummyFunc109,
  (void(*)(void))& dummyFunc110,
  (void(*)(void))& dummyFunc111,
  (void(*)(void))& dummyFunc112,
  (void(*)(void))& dummyFunc113,
  (void(*)(void))& dummyFunc114,
  (void(*)(void))& dummyFunc115,
  (void(*)(void))& dummyFunc116,
  (void(*)(void))& dummyFunc117,
  (void(*)(void))& dummyFunc118,
  (void(*)(void))& dummyFunc119,
  (void(*)(void))& dummyFunc120,
  (void(*)(void))& dummyFunc121,
  (void(*)(void))& dummyFunc122,
  (void(*)(void))& dummyFunc123,
  (void(*)(void))& dummyFunc124,
  (void(*)(void))& dummyFunc125,
  (void(*)(void))& dummyFunc126,
  (void(*)(void))& dummyFunc127,
  (void(*)(void))& dummyFunc128,
  (void(*)(void))& dummyFunc129,
  (void(*)(void))& dummyFunc130,
  (void(*)(void))& dummyFunc131,
  (void(*)(void))& dummyFunc132,
  (void(*)(void))& dummyFunc133,
  (void(*)(void))& dummyFunc134,
  (void(*)(void))& dummyFunc135,
  (void(*)(void))& dummyFunc136,
  (void(*)(void))& dummyFunc137,
  (void(*)(void))& dummyFunc138,
  (void(*)(void))& dummyFunc139,
  (void(*)(void))& dummyFunc140,
  (void(*)(void))& dummyFunc141,
  (void(*)(void))& dummyFunc142,
  (void(*)(void))& dummyFunc143,
  (void(*)(void))& dummyFunc144,
  (void(*)(void))& dummyFunc145,
  (void(*)(void))& dummyFunc146,
  (void(*)(void))& dummyFunc147,
  (void(*)(void))& dummyFunc148,
  (void(*)(void))& dummyFunc149,
  (void(*)(void))& dummyFunc150,
  (void(*)(void))& dummyFunc151,
  (void(*)(void))& dummyFunc152,
  (void(*)(void))& dummyFunc153,
  (void(*)(void))& dummyFunc154,
  (void(*)(void))& dummyFunc155,
  (void(*)(void))& dummyFunc156,
  (void(*)(void))& dummyFunc157,
  (void(*)(void))& dummyFunc158,
  (void(*)(void))& dummyFunc159,
  (void(*)(void))& dummyFunc160,
  (void(*)(void))& dummyFunc161,
  (void(*)(void))& dummyFunc162,
  (void(*)(void))& dummyFunc163,
  (void(*)(void))& dummyFunc164,
  (void(*)(void))& dummyFunc165,
  (void(*)(void))& dummyFunc166,
  (void(*)(void))& dummyFunc167,
  (void(*)(void))& dummyFunc168,
  (void(*)(void))& dummyFunc169,
  (void(*)(void))& dummyFunc170,
  (void(*)(void))& dummyFunc171,
  (void(*)(void))& dummyFunc172,
  (void(*)(void))& dummyFunc173,
  (void(*)(void))& dummyFunc174,
  (void(*)(void))& dummyFunc175,
  (void(*)(void))& dummyFunc176,
  (void(*)(void))& dummyFunc177,
  (void(*)(void))& dummyFunc178,
  (void(*)(void))& dummyFunc179,
  (void(*)(void))& dummyFunc180,
  (void(*)(void))& dummyFunc181,
  (void(*)(void))& dummyFunc182
};
