/**
Copyright (c) 2012-2020, Brice Videau <bvideau@anl.gov>
Copyright (c) 2012-2020, Vincent Danjean <Vincent.Danjean@ens-lyon.org>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Do not edit this file. It is automatically generated.

*/
#include <stdlib.h>
#include <stdio.h>
#pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wcpp"
#  define CL_USE_DEPRECATED_OPENCL_1_0_APIS
#  define CL_USE_DEPRECATED_OPENCL_1_1_APIS
#  define CL_USE_DEPRECATED_OPENCL_1_2_APIS
#  define CL_USE_DEPRECATED_OPENCL_2_0_APIS
#  define CL_USE_DEPRECATED_OPENCL_2_1_APIS
#  define CL_USE_DEPRECATED_OPENCL_2_2_APIS
#  define CL_TARGET_OPENCL_VERSION 300
#  include <CL/opencl.h>
#include <CL/cl.h>
#include <CL/cl_gl.h>
#include <CL/cl_egl.h>
#include <CL/cl_ext.h>
#pragma GCC diagnostic pop


CL_API_ENTRY cl_int CL_API_CALL 
clGetPlatformInfo(cl_platform_id   /* platform */, 
                  cl_platform_info /* param_name */,
                  size_t           /* param_value_size */, 
                  void *           /* param_value */,
                  size_t *         /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetDeviceIDs(cl_platform_id   /* platform */,
               cl_device_type   /* device_type */, 
               cl_uint          /* num_entries */, 
               cl_device_id *   /* devices */, 
               cl_uint *        /* num_devices */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetDeviceInfo(cl_device_id    /* device */,
                cl_device_info  /* param_name */, 
                size_t          /* param_value_size */, 
                void *          /* param_value */,
                size_t *        /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_context CL_API_CALL
clCreateContext(const cl_context_properties * /* properties */,
                cl_uint                       /* num_devices */,
                const cl_device_id *          /* devices */,
                void (CL_CALLBACK * /* pfn_notify */)(const char *, const void *, size_t, void *),
                void *                        /* user_data */,
                cl_int *                      /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_context CL_API_CALL
clCreateContextFromType(const cl_context_properties * /* properties */,
                        cl_device_type                /* device_type */,
                        void (CL_CALLBACK *     /* pfn_notify*/ )(const char *, const void *, size_t, void *),
                        void *                        /* user_data */,
                        cl_int *                      /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clRetainContext(cl_context /* context */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseContext(cl_context /* context */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetContextInfo(cl_context         /* context */, 
                 cl_context_info    /* param_name */, 
                 size_t             /* param_value_size */, 
                 void *             /* param_value */, 
                 size_t *           /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_command_queue CL_API_CALL
clCreateCommandQueue(cl_context                     /* context */, 
                     cl_device_id                   /* device */, 
                     cl_command_queue_properties    /* properties */,
                     cl_int *                       /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clRetainCommandQueue(cl_command_queue /* command_queue */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseCommandQueue(cl_command_queue /* command_queue */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetCommandQueueInfo(cl_command_queue      /* command_queue */,
                      cl_command_queue_info /* param_name */,
                      size_t                /* param_value_size */,
                      void *                /* param_value */,
                      size_t *              /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clSetCommandQueueProperty(cl_command_queue              /* command_queue */,
                          cl_command_queue_properties   /* properties */, 
                          cl_bool                        /* enable */,
                          cl_command_queue_properties * /* old_properties */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateBuffer(cl_context   /* context */,
               cl_mem_flags /* flags */,
               size_t       /* size */,
               void *       /* host_ptr */,
               cl_int *     /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateImage2D(cl_context              /* context */,
                cl_mem_flags            /* flags */,
                const cl_image_format * /* image_format */,
                size_t                  /* image_width */,
                size_t                  /* image_height */,
                size_t                  /* image_row_pitch */, 
                void *                  /* host_ptr */,
                cl_int *                /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateImage3D(cl_context              /* context */,
                cl_mem_flags            /* flags */,
                const cl_image_format * /* image_format */,
                size_t                  /* image_width */, 
                size_t                  /* image_height */,
                size_t                  /* image_depth */, 
                size_t                  /* image_row_pitch */, 
                size_t                  /* image_slice_pitch */, 
                void *                  /* host_ptr */,
                cl_int *                /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clRetainMemObject(cl_mem /* memobj */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseMemObject(cl_mem /* memobj */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetSupportedImageFormats(cl_context           /* context */,
                           cl_mem_flags         /* flags */,
                           cl_mem_object_type   /* image_type */,
                           cl_uint              /* num_entries */,
                           cl_image_format *    /* image_formats */,
                           cl_uint *            /* num_image_formats */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetMemObjectInfo(cl_mem           /* memobj */,
                   cl_mem_info      /* param_name */, 
                   size_t           /* param_value_size */,
                   void *           /* param_value */,
                   size_t *         /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetImageInfo(cl_mem           /* image */,
               cl_image_info    /* param_name */, 
               size_t           /* param_value_size */,
               void *           /* param_value */,
               size_t *         /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_sampler CL_API_CALL
clCreateSampler(cl_context          /* context */,
                cl_bool             /* normalized_coords */, 
                cl_addressing_mode  /* addressing_mode */, 
                cl_filter_mode      /* filter_mode */,
                cl_int *            /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clRetainSampler(cl_sampler /* sampler */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseSampler(cl_sampler /* sampler */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetSamplerInfo(cl_sampler         /* sampler */,
                 cl_sampler_info    /* param_name */,
                 size_t             /* param_value_size */,
                 void *             /* param_value */,
                 size_t *           /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithSource(cl_context        /* context */,
                          cl_uint           /* count */,
                          const char **     /* strings */,
                          const size_t *    /* lengths */,
                          cl_int *          /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithBinary(cl_context                     /* context */,
                          cl_uint                        /* num_devices */,
                          const cl_device_id *           /* device_list */,
                          const size_t *                 /* lengths */,
                          const unsigned char **         /* binaries */,
                          cl_int *                       /* binary_status */,
                          cl_int *                       /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clRetainProgram(cl_program /* program */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseProgram(cl_program /* program */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clBuildProgram(cl_program           /* program */,
               cl_uint              /* num_devices */,
               const cl_device_id * /* device_list */,
               const char *         /* options */, 
               void (CL_CALLBACK *  /* pfn_notify */)(cl_program /* program */, void * /* user_data */),
               void *               /* user_data */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetProgramInfo(cl_program         /* program */,
                 cl_program_info    /* param_name */,
                 size_t             /* param_value_size */,
                 void *             /* param_value */,
                 size_t *           /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetProgramBuildInfo(cl_program            /* program */,
                      cl_device_id          /* device */,
                      cl_program_build_info /* param_name */,
                      size_t                /* param_value_size */,
                      void *                /* param_value */,
                      size_t *              /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_kernel CL_API_CALL
clCreateKernel(cl_program      /* program */,
               const char *    /* kernel_name */,
               cl_int *        /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clCreateKernelsInProgram(cl_program     /* program */,
                         cl_uint        /* num_kernels */,
                         cl_kernel *    /* kernels */,
                         cl_uint *      /* num_kernels_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clRetainKernel(cl_kernel    /* kernel */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseKernel(cl_kernel   /* kernel */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clSetKernelArg(cl_kernel    /* kernel */,
               cl_uint      /* arg_index */,
               size_t       /* arg_size */,
               const void * /* arg_value */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetKernelInfo(cl_kernel       /* kernel */,
                cl_kernel_info  /* param_name */,
                size_t          /* param_value_size */,
                void *          /* param_value */,
                size_t *        /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetKernelWorkGroupInfo(cl_kernel                  /* kernel */,
                         cl_device_id               /* device */,
                         cl_kernel_work_group_info  /* param_name */,
                         size_t                     /* param_value_size */,
                         void *                     /* param_value */,
                         size_t *                   /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clWaitForEvents(cl_uint             /* num_events */,
                const cl_event *    /* event_list */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetEventInfo(cl_event         /* event */,
               cl_event_info    /* param_name */,
               size_t           /* param_value_size */,
               void *           /* param_value */,
               size_t *         /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clRetainEvent(cl_event /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseEvent(cl_event /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetEventProfilingInfo(cl_event            /* event */,
                        cl_profiling_info   /* param_name */,
                        size_t              /* param_value_size */,
                        void *              /* param_value */,
                        size_t *            /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clFlush(cl_command_queue /* command_queue */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clFinish(cl_command_queue /* command_queue */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReadBuffer(cl_command_queue    /* command_queue */,
                    cl_mem              /* buffer */,
                    cl_bool             /* blocking_read */,
                    size_t              /* offset */,
                    size_t              /* cb */, 
                    void *              /* ptr */,
                    cl_uint             /* num_events_in_wait_list */,
                    const cl_event *    /* event_wait_list */,
                    cl_event *          /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWriteBuffer(cl_command_queue   /* command_queue */, 
                     cl_mem             /* buffer */, 
                     cl_bool            /* blocking_write */, 
                     size_t             /* offset */, 
                     size_t             /* cb */, 
                     const void *       /* ptr */, 
                     cl_uint            /* num_events_in_wait_list */, 
                     const cl_event *   /* event_wait_list */, 
                     cl_event *         /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyBuffer(cl_command_queue    /* command_queue */, 
                    cl_mem              /* src_buffer */,
                    cl_mem              /* dst_buffer */, 
                    size_t              /* src_offset */,
                    size_t              /* dst_offset */,
                    size_t              /* cb */, 
                    cl_uint             /* num_events_in_wait_list */,
                    const cl_event *    /* event_wait_list */,
                    cl_event *          /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReadImage(cl_command_queue     /* command_queue */,
                   cl_mem               /* image */,
                   cl_bool              /* blocking_read */, 
                   const size_t *       /* origin[3] */,
                   const size_t *       /* region[3] */,
                   size_t               /* row_pitch */,
                   size_t               /* slice_pitch */, 
                   void *               /* ptr */,
                   cl_uint              /* num_events_in_wait_list */,
                   const cl_event *     /* event_wait_list */,
                   cl_event *           /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWriteImage(cl_command_queue    /* command_queue */,
                    cl_mem              /* image */,
                    cl_bool             /* blocking_write */, 
                    const size_t *      /* origin[3] */,
                    const size_t *      /* region[3] */,
                    size_t              /* input_row_pitch */,
                    size_t              /* input_slice_pitch */, 
                    const void *        /* ptr */,
                    cl_uint             /* num_events_in_wait_list */,
                    const cl_event *    /* event_wait_list */,
                    cl_event *          /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyImage(cl_command_queue     /* command_queue */,
                   cl_mem               /* src_image */,
                   cl_mem               /* dst_image */, 
                   const size_t *       /* src_origin[3] */,
                   const size_t *       /* dst_origin[3] */,
                   const size_t *       /* region[3] */, 
                   cl_uint              /* num_events_in_wait_list */,
                   const cl_event *     /* event_wait_list */,
                   cl_event *           /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyImageToBuffer(cl_command_queue /* command_queue */,
                           cl_mem           /* src_image */,
                           cl_mem           /* dst_buffer */, 
                           const size_t *   /* src_origin[3] */,
                           const size_t *   /* region[3] */, 
                           size_t           /* dst_offset */,
                           cl_uint          /* num_events_in_wait_list */,
                           const cl_event * /* event_wait_list */,
                           cl_event *       /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyBufferToImage(cl_command_queue /* command_queue */,
                           cl_mem           /* src_buffer */,
                           cl_mem           /* dst_image */, 
                           size_t           /* src_offset */,
                           const size_t *   /* dst_origin[3] */,
                           const size_t *   /* region[3] */, 
                           cl_uint          /* num_events_in_wait_list */,
                           const cl_event * /* event_wait_list */,
                           cl_event *       /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY void * CL_API_CALL
clEnqueueMapBuffer(cl_command_queue /* command_queue */,
                   cl_mem           /* buffer */,
                   cl_bool          /* blocking_map */, 
                   cl_map_flags     /* map_flags */,
                   size_t           /* offset */,
                   size_t           /* cb */,
                   cl_uint          /* num_events_in_wait_list */,
                   const cl_event * /* event_wait_list */,
                   cl_event *       /* event */,
                   cl_int *         /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY void * CL_API_CALL
clEnqueueMapImage(cl_command_queue  /* command_queue */,
                  cl_mem            /* image */, 
                  cl_bool           /* blocking_map */, 
                  cl_map_flags      /* map_flags */, 
                  const size_t *    /* origin[3] */,
                  const size_t *    /* region[3] */,
                  size_t *          /* image_row_pitch */,
                  size_t *          /* image_slice_pitch */,
                  cl_uint           /* num_events_in_wait_list */,
                  const cl_event *  /* event_wait_list */,
                  cl_event *        /* event */,
                  cl_int *          /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueUnmapMemObject(cl_command_queue /* command_queue */,
                        cl_mem           /* memobj */,
                        void *           /* mapped_ptr */,
                        cl_uint          /* num_events_in_wait_list */,
                        const cl_event *  /* event_wait_list */,
                        cl_event *        /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueNDRangeKernel(cl_command_queue /* command_queue */,
                       cl_kernel        /* kernel */,
                       cl_uint          /* work_dim */,
                       const size_t *   /* global_work_offset */,
                       const size_t *   /* global_work_size */,
                       const size_t *   /* local_work_size */,
                       cl_uint          /* num_events_in_wait_list */,
                       const cl_event * /* event_wait_list */,
                       cl_event *       /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueTask(cl_command_queue  /* command_queue */,
              cl_kernel         /* kernel */,
              cl_uint           /* num_events_in_wait_list */,
              const cl_event *  /* event_wait_list */,
              cl_event *        /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueNativeKernel(cl_command_queue  /* command_queue */,
					  void (*user_func)(void *), 
                      void *            /* args */,
                      size_t            /* cb_args */, 
                      cl_uint           /* num_mem_objects */,
                      const cl_mem *    /* mem_list */,
                      const void **     /* args_mem_loc */,
                      cl_uint           /* num_events_in_wait_list */,
                      const cl_event *  /* event_wait_list */,
                      cl_event *        /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueMarker(cl_command_queue    /* command_queue */,
                cl_event *          /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWaitForEvents(cl_command_queue /* command_queue */,
                       cl_uint          /* num_events */,
                       const cl_event * /* event_list */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueBarrier(cl_command_queue /* command_queue */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY void * CL_API_CALL
clGetExtensionFunctionAddress(const char * /* func_name */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLBuffer(cl_context     /* context */,
                     cl_mem_flags   /* flags */,
                     cl_GLuint      /* bufobj */,
                     int *          /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLTexture2D(cl_context      /* context */,
                        cl_mem_flags    /* flags */,
                        cl_GLenum       /* target */,
                        cl_GLint        /* miplevel */,
                        cl_GLuint       /* texture */,
                        cl_int *        /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLTexture3D(cl_context      /* context */,
                        cl_mem_flags    /* flags */,
                        cl_GLenum       /* target */,
                        cl_GLint        /* miplevel */,
                        cl_GLuint       /* texture */,
                        cl_int *        /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLRenderbuffer(cl_context   /* context */,
                           cl_mem_flags /* flags */,
                           cl_GLuint    /* renderbuffer */,
                           cl_int *     /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetGLObjectInfo(cl_mem                /* memobj */,
                  cl_gl_object_type *   /* gl_object_type */,
                  cl_GLuint *              /* gl_object_name */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetGLTextureInfo(cl_mem               /* memobj */,
                   cl_gl_texture_info   /* param_name */,
                   size_t               /* param_value_size */,
                   void *               /* param_value */,
                   size_t *             /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueAcquireGLObjects(cl_command_queue      /* command_queue */,
                          cl_uint               /* num_objects */,
                          const cl_mem *        /* mem_objects */,
                          cl_uint               /* num_events_in_wait_list */,
                          const cl_event *      /* event_wait_list */,
                          cl_event *            /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReleaseGLObjects(cl_command_queue      /* command_queue */,
                          cl_uint               /* num_objects */,
                          const cl_mem *        /* mem_objects */,
                          cl_uint               /* num_events_in_wait_list */,
                          const cl_event *      /* event_wait_list */,
                          cl_event *            /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetGLContextInfoKHR(const cl_context_properties * /* properties */,
                      cl_gl_context_info            /* param_name */,
                      size_t                        /* param_value_size */,
                      void *                        /* param_value */,
                      size_t *                      /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clSetEventCallback(cl_event    /* event */,
                   cl_int      /* command_exec_callback_type */,
                   void (CL_CALLBACK * /* pfn_notify */)(cl_event, cl_int, void *),
                   void *      /* user_data */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateSubBuffer(cl_mem                   /* buffer */,
                  cl_mem_flags             /* flags */,
                  cl_buffer_create_type    /* buffer_create_type */,
                  const void *             /* buffer_create_info */,
                  cl_int *                 /* errcode_ret */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clSetMemObjectDestructorCallback(cl_mem /* memobj */,
                                 void (CL_CALLBACK * /*pfn_notify*/)( cl_mem /* memobj */, void* /*user_data*/),
                                 void * /*user_data */ )             CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_event CL_API_CALL
clCreateUserEvent(cl_context    /* context */,
                  cl_int *      /* errcode_ret */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clSetUserEventStatus(cl_event   /* event */,
                     cl_int     /* execution_status */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReadBufferRect(cl_command_queue    /* command_queue */,
                        cl_mem              /* buffer */,
                        cl_bool             /* blocking_read */,
                        const size_t *      /* buffer_origin */,
                        const size_t *      /* host_origin */, 
                        const size_t *      /* region */,
                        size_t              /* buffer_row_pitch */,
                        size_t              /* buffer_slice_pitch */,
                        size_t              /* host_row_pitch */,
                        size_t              /* host_slice_pitch */,                        
                        void *              /* ptr */,
                        cl_uint             /* num_events_in_wait_list */,
                        const cl_event *    /* event_wait_list */,
                        cl_event *          /* event */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWriteBufferRect(cl_command_queue    /* command_queue */,
                         cl_mem              /* buffer */,
                         cl_bool             /* blocking_write */,
                         const size_t *      /* buffer_origin */,
                         const size_t *      /* host_origin */, 
                         const size_t *      /* region */,
                         size_t              /* buffer_row_pitch */,
                         size_t              /* buffer_slice_pitch */,
                         size_t              /* host_row_pitch */,
                         size_t              /* host_slice_pitch */,                        
                         const void *        /* ptr */,
                         cl_uint             /* num_events_in_wait_list */,
                         const cl_event *    /* event_wait_list */,
                         cl_event *          /* event */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyBufferRect(cl_command_queue    /* command_queue */, 
                        cl_mem              /* src_buffer */,
                        cl_mem              /* dst_buffer */, 
                        const size_t *      /* src_origin */,
                        const size_t *      /* dst_origin */,
                        const size_t *      /* region */, 
                        size_t              /* src_row_pitch */,
                        size_t              /* src_slice_pitch */,
                        size_t              /* dst_row_pitch */,
                        size_t              /* dst_slice_pitch */,
                        cl_uint             /* num_events_in_wait_list */,
                        const cl_event *    /* event_wait_list */,
                        cl_event *          /* event */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clCreateSubDevicesEXT(cl_device_id /*in_device*/,
                      const cl_device_partition_property_ext * /* properties */,
                      cl_uint /*num_entries*/,
                      cl_device_id * /*out_devices*/,
                      cl_uint * /*num_devices*/ ) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clRetainDeviceEXT( cl_device_id /*device*/ ) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseDeviceEXT( cl_device_id /*device*/ ) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_event CL_API_CALL
clCreateEventFromGLsyncKHR(cl_context           /* context */,
                           cl_GLsync            /* cl_GLsync */,
                           cl_int *             /* errcode_ret */) CL_API_SUFFIX__VERSION_1_1;
CL_API_ENTRY cl_int CL_API_CALL
clCreateSubDevices(cl_device_id                         /* in_device */,
                   const cl_device_partition_property * /* properties */,
                   cl_uint                              /* num_devices */,
                   cl_device_id *                       /* out_devices */,
                   cl_uint *                            /* num_devices_ret */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clRetainDevice(cl_device_id /* device */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clReleaseDevice(cl_device_id /* device */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateImage(cl_context              /* context */,
              cl_mem_flags            /* flags */,
              const cl_image_format * /* image_format */,
              const cl_image_desc *   /* image_desc */, 
              void *                  /* host_ptr */,
              cl_int *                /* errcode_ret */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithBuiltInKernels(cl_context            /* context */,
                                  cl_uint               /* num_devices */,
                                  const cl_device_id *  /* device_list */,
                                  const char *          /* kernel_names */,
                                  cl_int *              /* errcode_ret */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clCompileProgram(cl_program           /* program */,
                 cl_uint              /* num_devices */,
                 const cl_device_id * /* device_list */,
                 const char *         /* options */, 
                 cl_uint              /* num_input_headers */,
                 const cl_program *   /* input_headers */,
                 const char **        /* header_include_names */,
                 void (CL_CALLBACK *  /* pfn_notify */)(cl_program /* program */, void * /* user_data */),
                 void *               /* user_data */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_program CL_API_CALL
clLinkProgram(cl_context           /* context */,
              cl_uint              /* num_devices */,
              const cl_device_id * /* device_list */,
              const char *         /* options */, 
              cl_uint              /* num_input_programs */,
              const cl_program *   /* input_programs */,
              void (CL_CALLBACK *  /* pfn_notify */)(cl_program /* program */, void * /* user_data */),
              void *               /* user_data */,
              cl_int *             /* errcode_ret */ ) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clUnloadPlatformCompiler(cl_platform_id /* platform */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clGetKernelArgInfo(cl_kernel       /* kernel */,
                   cl_uint         /* arg_indx */,
                   cl_kernel_arg_info  /* param_name */,
                   size_t          /* param_value_size */,
                   void *          /* param_value */,
                   size_t *        /* param_value_size_ret */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueFillBuffer(cl_command_queue   /* command_queue */,
                    cl_mem             /* buffer */, 
                    const void *       /* pattern */, 
                    size_t             /* pattern_size */, 
                    size_t             /* offset */, 
                    size_t             /* size */, 
                    cl_uint            /* num_events_in_wait_list */, 
                    const cl_event *   /* event_wait_list */, 
                    cl_event *         /* event */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueFillImage(cl_command_queue   /* command_queue */,
                   cl_mem             /* image */, 
                   const void *       /* fill_color */, 
                   const size_t *     /* origin[3] */, 
                   const size_t *     /* region[3] */, 
                   cl_uint            /* num_events_in_wait_list */, 
                   const cl_event *   /* event_wait_list */, 
                   cl_event *         /* event */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueMigrateMemObjects(cl_command_queue       /* command_queue */,
                           cl_uint                /* num_mem_objects */,
                           const cl_mem *         /* mem_objects */,
                           cl_mem_migration_flags /* flags */,
                           cl_uint                /* num_events_in_wait_list */,
                           const cl_event *       /* event_wait_list */,
                           cl_event *             /* event */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueMarkerWithWaitList(cl_command_queue /* command_queue */,
                            cl_uint           /* num_events_in_wait_list */,
                            const cl_event *  /* event_wait_list */,
                            cl_event *        /* event */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueBarrierWithWaitList(cl_command_queue /* command_queue */,
                             cl_uint           /* num_events_in_wait_list */,
                             const cl_event *  /* event_wait_list */,
                             cl_event *        /* event */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY void * CL_API_CALL 
clGetExtensionFunctionAddressForPlatform(cl_platform_id /* platform */,
                                         const char *   /* func_name */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLTexture(cl_context      /* context */,
                      cl_mem_flags    /* flags */,
                      cl_GLenum       /* target */,
                      cl_GLint        /* miplevel */,
                      cl_GLuint       /* texture */,
                      cl_int *        /* errcode_ret */) CL_API_SUFFIX__VERSION_1_2;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromEGLImageKHR(cl_context                  /* context */,
                        CLeglDisplayKHR             /* egldisplay */,
                        CLeglImageKHR               /* eglimage */,
                        cl_mem_flags                /* flags */,
                        const cl_egl_image_properties_khr * /* properties */,
                        cl_int *                    /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueAcquireEGLObjectsKHR(cl_command_queue /* command_queue */,
                              cl_uint          /* num_objects */,
                              const cl_mem *   /* mem_objects */,
                              cl_uint          /* num_events_in_wait_list */,
                              const cl_event * /* event_wait_list */,
                              cl_event *       /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReleaseEGLObjectsKHR(cl_command_queue /* command_queue */,
                              cl_uint          /* num_objects */,
                              const cl_mem *   /* mem_objects */,
                              cl_uint          /* num_events_in_wait_list */,
                              const cl_event * /* event_wait_list */,
                              cl_event *       /* event */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_event CL_API_CALL
clCreateEventFromEGLSyncKHR(cl_context      /* context */,
                            CLeglSyncKHR    /* sync */,
                            CLeglDisplayKHR /* display */,
                            cl_int *        /* errcode_ret */) CL_API_SUFFIX__VERSION_1_0;
CL_API_ENTRY cl_command_queue CL_API_CALL
clCreateCommandQueueWithProperties(cl_context               /* context */,
                                   cl_device_id             /* device */,
                                   const cl_queue_properties *    /* properties */,
                                   cl_int *                 /* errcode_ret */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreatePipe(cl_context                 /* context */,
             cl_mem_flags               /* flags */,
             cl_uint                    /* pipe_packet_size */,
             cl_uint                    /* pipe_max_packets */,
             const cl_pipe_properties * /* properties */,
             cl_int *                   /* errcode_ret */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetPipeInfo(cl_mem           /* pipe */,
              cl_pipe_info     /* param_name */,
              size_t           /* param_value_size */,
              void *           /* param_value */,
              size_t *         /* param_value_size_ret */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY void * CL_API_CALL
clSVMAlloc(cl_context       /* context */,
           cl_svm_mem_flags /* flags */,
           size_t           /* size */,
           cl_uint          /* alignment */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY void CL_API_CALL
clSVMFree(cl_context        /* context */,
          void *            /* svm_pointer */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMFree(cl_command_queue  /* command_queue */,
                 cl_uint           /* num_svm_pointers */,
                 void *[]          /* svm_pointers[] */,
                 void (CL_CALLBACK * /*pfn_free_func*/)(cl_command_queue /* queue */,
                                                        cl_uint          /* num_svm_pointers */,
                                                        void *[]         /* svm_pointers[] */,
                                                        void *           /* user_data */),
                 void *            /* user_data */,
                 cl_uint           /* num_events_in_wait_list */,
                 const cl_event *  /* event_wait_list */,
                 cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMemcpy(cl_command_queue  /* command_queue */,
                   cl_bool           /* blocking_copy */,
                   void *            /* dst_ptr */,
                   const void *      /* src_ptr */,
                   size_t            /* size */,
                   cl_uint           /* num_events_in_wait_list */,
                   const cl_event *  /* event_wait_list */,
                   cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMemFill(cl_command_queue  /* command_queue */,
                    void *            /* svm_ptr */,
                    const void *      /* pattern */,
                    size_t            /* pattern_size */,
                    size_t            /* size */,
                    cl_uint           /* num_events_in_wait_list */,
                    const cl_event *  /* event_wait_list */,
                    cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMap(cl_command_queue  /* command_queue */,
                cl_bool           /* blocking_map */,
                cl_map_flags      /* flags */,
                void *            /* svm_ptr */,
                size_t            /* size */,
                cl_uint           /* num_events_in_wait_list */,
                const cl_event *  /* event_wait_list */,
                cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMUnmap(cl_command_queue  /* command_queue */,
                  void *            /* svm_ptr */,
                  cl_uint           /* num_events_in_wait_list */,
                  const cl_event *  /* event_wait_list */,
                  cl_event *        /* event */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_sampler CL_API_CALL
clCreateSamplerWithProperties(cl_context                     /* context */,
                              const cl_sampler_properties *  /* normalized_coords */,
                              cl_int *                       /* errcode_ret */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clSetKernelArgSVMPointer(cl_kernel    /* kernel */,
                         cl_uint      /* arg_index */,
                         const void * /* arg_value */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clSetKernelExecInfo(cl_kernel            /* kernel */,
                    cl_kernel_exec_info  /* param_name */,
                    size_t               /* param_value_size */,
                    const void *         /* param_value */) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_int CL_API_CALL
clGetKernelSubGroupInfoKHR(cl_kernel /* in_kernel */,
                           cl_device_id /*in_device*/,
                           cl_kernel_sub_group_info /* param_name */,
                           size_t /*input_value_size*/,
                           const void * /*input_value*/,
                           size_t /*param_value_size*/,
                           void* /*param_value*/,
                           size_t* /*param_value_size_ret*/ ) CL_API_SUFFIX__VERSION_2_0;
CL_API_ENTRY cl_kernel CL_API_CALL
clCloneKernel(cl_kernel     /* source_kernel */,
              cl_int*       /* errcode_ret */) CL_API_SUFFIX__VERSION_2_1;
CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithIL(cl_context    /* context */,
                      const void*    /* il */,
                      size_t         /* length */,
                      cl_int*        /* errcode_ret */) CL_API_SUFFIX__VERSION_2_1;
CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMigrateMem(cl_command_queue         /* command_queue */,
                       cl_uint                  /* num_svm_pointers */,
                       const void **            /* svm_pointers */,
                       const size_t *           /* sizes */,
                       cl_mem_migration_flags   /* flags */,
                       cl_uint                  /* num_events_in_wait_list */,
                       const cl_event *         /* event_wait_list */,
                       cl_event *               /* event */) CL_API_SUFFIX__VERSION_2_1;
CL_API_ENTRY cl_int CL_API_CALL
clGetDeviceAndHostTimer(cl_device_id    /* device */,
                        cl_ulong*       /* device_timestamp */,
                        cl_ulong*       /* host_timestamp */) CL_API_SUFFIX__VERSION_2_1;
CL_API_ENTRY cl_int CL_API_CALL
clGetHostTimer(cl_device_id /* device */,
               cl_ulong *   /* host_timestamp */)  CL_API_SUFFIX__VERSION_2_1;
CL_API_ENTRY cl_int CL_API_CALL
clGetKernelSubGroupInfo(cl_kernel                   /* kernel */,
                        cl_device_id                /* device */,
                        cl_kernel_sub_group_info    /* param_name */,
                        size_t                      /* input_value_size */,
                        const void*                 /* input_value */,
                        size_t                      /* param_value_size */,
                        void*                       /* param_value */,
                        size_t*                     /* param_value_size_ret */ ) CL_API_SUFFIX__VERSION_2_1;
CL_API_ENTRY cl_int CL_API_CALL
clSetDefaultDeviceCommandQueue(cl_context           /* context */,
                               cl_device_id         /* device */,
                               cl_command_queue     /* command_queue */) CL_API_SUFFIX__VERSION_2_1;
CL_API_ENTRY cl_int CL_API_CALL
clSetProgramReleaseCallback(cl_program          /* program */,
                            void (CL_CALLBACK * /* pfn_notify */)(cl_program /* program */, void * /* user_data */),
                            void *              /* user_data */) CL_API_SUFFIX__VERSION_2_2;
CL_API_ENTRY cl_int CL_API_CALL
clSetProgramSpecializationConstant(cl_program  /* program */,
                                   cl_uint     /* spec_id */,
                                   size_t      /* spec_size */,
                                   const void* /* spec_value */) CL_API_SUFFIX__VERSION_2_2;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateBufferWithProperties(cl_context                /* context */,
                             const cl_mem_properties * /* properties */,
                             cl_mem_flags              /* flags */,
                             size_t                    /* size */,
                             void *                    /* host_ptr */,
                             cl_int *                  /* errcode_ret */) CL_API_SUFFIX__VERSION_3_0;
CL_API_ENTRY cl_mem CL_API_CALL
clCreateImageWithProperties(cl_context                /* context */,
                            const cl_mem_properties * /* properties */,
                            cl_mem_flags              /* flags */,
                            const cl_image_format *   /* image_format */,
                            const cl_image_desc *     /* image_desc */,
                            void *                    /* host_ptr */,
                            cl_int *                  /* errcode_ret */) CL_API_SUFFIX__VERSION_3_0;
CL_API_ENTRY cl_int CL_API_CALL
clSetContextDestructorCallback(cl_context          /* context */,
                               void (CL_CALLBACK * /* pfn_notify */)(cl_context /* context */, void* /* user_data */),
                               void *              /* user_data */) CL_API_SUFFIX__VERSION_3_0;


void call_all_OpenCL_functions(cl_platform_id chosen_platform) {
  cl_context_properties properties[] = { CL_CONTEXT_PLATFORM, (cl_context_properties)chosen_platform, 0 };
  clGetPlatformInfo((cl_platform_id )chosen_platform,( cl_platform_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetPlatformInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("1  : %s (expected)\n", "clGetPlatformInfo");
#endif
  fflush(NULL);
  clGetDeviceIDs((cl_platform_id )chosen_platform,( cl_device_type )0,( cl_uint )0,( cl_device_id * )0,( cl_uint *)0);
  printf("%s\n", "clGetDeviceIDs");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("2  : %s (expected)\n", "clGetDeviceIDs");
#endif
  fflush(NULL);
  clGetDeviceInfo((cl_device_id )chosen_platform,( cl_device_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetDeviceInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("3  : %s (expected)\n", "clGetDeviceInfo");
#endif
  fflush(NULL);
  clCreateContext(properties,1,(cl_device_id*)&chosen_platform,NULL,NULL,NULL);
  printf("%s\n", "clCreateContext");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("4  : %s (expected)\n", "clCreateContext");
#endif
  fflush(NULL);
  clCreateContextFromType(properties,CL_DEVICE_TYPE_CPU,NULL,NULL,NULL);
  printf("%s\n", "clCreateContextFromType");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("5  : %s (expected)\n", "clCreateContextFromType");
#endif
  fflush(NULL);
  clRetainContext((cl_context)chosen_platform);
  printf("%s\n", "clRetainContext");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("6  : %s (expected)\n", "clRetainContext");
#endif
  fflush(NULL);
  clReleaseContext((cl_context)chosen_platform);
  printf("%s\n", "clReleaseContext");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("7  : %s (expected)\n", "clReleaseContext");
#endif
  fflush(NULL);
  clGetContextInfo((cl_context )chosen_platform,( cl_context_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetContextInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("8  : %s (expected)\n", "clGetContextInfo");
#endif
  fflush(NULL);
  clCreateCommandQueue((cl_context )chosen_platform,( cl_device_id )0,( cl_command_queue_properties )0,( cl_int *)0);
  printf("%s\n", "clCreateCommandQueue");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("9  : %s (expected)\n", "clCreateCommandQueue");
#endif
  fflush(NULL);
  clRetainCommandQueue((cl_command_queue)chosen_platform);
  printf("%s\n", "clRetainCommandQueue");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("10  : %s (expected)\n", "clRetainCommandQueue");
#endif
  fflush(NULL);
  clReleaseCommandQueue((cl_command_queue)chosen_platform);
  printf("%s\n", "clReleaseCommandQueue");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("11  : %s (expected)\n", "clReleaseCommandQueue");
#endif
  fflush(NULL);
  clGetCommandQueueInfo((cl_command_queue )chosen_platform,( cl_command_queue_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetCommandQueueInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("12  : %s (expected)\n", "clGetCommandQueueInfo");
#endif
  fflush(NULL);
  clSetCommandQueueProperty((cl_command_queue )chosen_platform,( cl_command_queue_properties )0,( cl_bool )0,( cl_command_queue_properties *)0);
  printf("%s\n", "clSetCommandQueueProperty");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("13  : %s (expected)\n", "clSetCommandQueueProperty");
#endif
  fflush(NULL);
  clCreateBuffer((cl_context )chosen_platform,( cl_mem_flags )0,( size_t )0,( void * )0,( cl_int *)0);
  printf("%s\n", "clCreateBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("14  : %s (expected)\n", "clCreateBuffer");
#endif
  fflush(NULL);
  clCreateImage2D((cl_context )chosen_platform,( cl_mem_flags )0,( const cl_image_format * )0,( size_t )0,( size_t )0,( size_t )0,( void * )0,( cl_int *)0);
  printf("%s\n", "clCreateImage2D");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("15  : %s (expected)\n", "clCreateImage2D");
#endif
  fflush(NULL);
  clCreateImage3D((cl_context )chosen_platform,( cl_mem_flags )0,( const cl_image_format * )0,( size_t )0,( size_t )0,( size_t )0,( size_t )0,( size_t )0,( void * )0,( cl_int *)0);
  printf("%s\n", "clCreateImage3D");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("16  : %s (expected)\n", "clCreateImage3D");
#endif
  fflush(NULL);
  clRetainMemObject((cl_mem)chosen_platform);
  printf("%s\n", "clRetainMemObject");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("17  : %s (expected)\n", "clRetainMemObject");
#endif
  fflush(NULL);
  clReleaseMemObject((cl_mem)chosen_platform);
  printf("%s\n", "clReleaseMemObject");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("18  : %s (expected)\n", "clReleaseMemObject");
#endif
  fflush(NULL);
  clGetSupportedImageFormats((cl_context )chosen_platform,( cl_mem_flags )0,( cl_mem_object_type )0,( cl_uint )0,( cl_image_format * )0,( cl_uint *)0);
  printf("%s\n", "clGetSupportedImageFormats");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("19  : %s (expected)\n", "clGetSupportedImageFormats");
#endif
  fflush(NULL);
  clGetMemObjectInfo((cl_mem )chosen_platform,( cl_mem_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetMemObjectInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("20  : %s (expected)\n", "clGetMemObjectInfo");
#endif
  fflush(NULL);
  clGetImageInfo((cl_mem )chosen_platform,( cl_image_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetImageInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("21  : %s (expected)\n", "clGetImageInfo");
#endif
  fflush(NULL);
  clCreateSampler((cl_context )chosen_platform,( cl_bool )0,( cl_addressing_mode )0,( cl_filter_mode )0,( cl_int *)0);
  printf("%s\n", "clCreateSampler");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("22  : %s (expected)\n", "clCreateSampler");
#endif
  fflush(NULL);
  clRetainSampler((cl_sampler)chosen_platform);
  printf("%s\n", "clRetainSampler");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("23  : %s (expected)\n", "clRetainSampler");
#endif
  fflush(NULL);
  clReleaseSampler((cl_sampler)chosen_platform);
  printf("%s\n", "clReleaseSampler");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("24  : %s (expected)\n", "clReleaseSampler");
#endif
  fflush(NULL);
  clGetSamplerInfo((cl_sampler )chosen_platform,( cl_sampler_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetSamplerInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("25  : %s (expected)\n", "clGetSamplerInfo");
#endif
  fflush(NULL);
  clCreateProgramWithSource((cl_context )chosen_platform,( cl_uint )0,( const char ** )0,( const size_t * )0,( cl_int *)0);
  printf("%s\n", "clCreateProgramWithSource");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("26  : %s (expected)\n", "clCreateProgramWithSource");
#endif
  fflush(NULL);
  clCreateProgramWithBinary((cl_context )chosen_platform,( cl_uint )0,( const cl_device_id * )0,( const size_t * )0,( const unsigned char ** )0,( cl_int * )0,( cl_int *)0);
  printf("%s\n", "clCreateProgramWithBinary");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("27  : %s (expected)\n", "clCreateProgramWithBinary");
#endif
  fflush(NULL);
  clRetainProgram((cl_program)chosen_platform);
  printf("%s\n", "clRetainProgram");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("28  : %s (expected)\n", "clRetainProgram");
#endif
  fflush(NULL);
  clReleaseProgram((cl_program)chosen_platform);
  printf("%s\n", "clReleaseProgram");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("29  : %s (expected)\n", "clReleaseProgram");
#endif
  fflush(NULL);
  clBuildProgram((cl_program )chosen_platform,( cl_uint )0,( const cl_device_id * )0,( const char * )0,( void (CL_CALLBACK * )(cl_program , void * ))0,( void *)0);
  printf("%s\n", "clBuildProgram");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("30  : %s (expected)\n", "clBuildProgram");
#endif
  fflush(NULL);
  clGetProgramInfo((cl_program )chosen_platform,( cl_program_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetProgramInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("32  : %s (expected)\n", "clGetProgramInfo");
#endif
  fflush(NULL);
  clGetProgramBuildInfo((cl_program )chosen_platform,( cl_device_id )0,( cl_program_build_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetProgramBuildInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("33  : %s (expected)\n", "clGetProgramBuildInfo");
#endif
  fflush(NULL);
  clCreateKernel((cl_program )chosen_platform,( const char * )0,( cl_int *)0);
  printf("%s\n", "clCreateKernel");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("34  : %s (expected)\n", "clCreateKernel");
#endif
  fflush(NULL);
  clCreateKernelsInProgram((cl_program )chosen_platform,( cl_uint )0,( cl_kernel * )0,( cl_uint *)0);
  printf("%s\n", "clCreateKernelsInProgram");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("35  : %s (expected)\n", "clCreateKernelsInProgram");
#endif
  fflush(NULL);
  clRetainKernel((cl_kernel)chosen_platform);
  printf("%s\n", "clRetainKernel");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("36  : %s (expected)\n", "clRetainKernel");
#endif
  fflush(NULL);
  clReleaseKernel((cl_kernel)chosen_platform);
  printf("%s\n", "clReleaseKernel");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("37  : %s (expected)\n", "clReleaseKernel");
#endif
  fflush(NULL);
  clSetKernelArg((cl_kernel )chosen_platform,( cl_uint )0,( size_t )0,( const void *)0);
  printf("%s\n", "clSetKernelArg");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("38  : %s (expected)\n", "clSetKernelArg");
#endif
  fflush(NULL);
  clGetKernelInfo((cl_kernel )chosen_platform,( cl_kernel_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetKernelInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("39  : %s (expected)\n", "clGetKernelInfo");
#endif
  fflush(NULL);
  clGetKernelWorkGroupInfo((cl_kernel )chosen_platform,( cl_device_id )0,( cl_kernel_work_group_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetKernelWorkGroupInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("40  : %s (expected)\n", "clGetKernelWorkGroupInfo");
#endif
  fflush(NULL);
  clWaitForEvents(1,(cl_event*)&chosen_platform);
  printf("%s\n", "clWaitForEvents");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("41  : %s (expected)\n", "clWaitForEvents");
#endif
  fflush(NULL);
  clGetEventInfo((cl_event )chosen_platform,( cl_event_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetEventInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("42  : %s (expected)\n", "clGetEventInfo");
#endif
  fflush(NULL);
  clRetainEvent((cl_event)chosen_platform);
  printf("%s\n", "clRetainEvent");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("43  : %s (expected)\n", "clRetainEvent");
#endif
  fflush(NULL);
  clReleaseEvent((cl_event)chosen_platform);
  printf("%s\n", "clReleaseEvent");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("44  : %s (expected)\n", "clReleaseEvent");
#endif
  fflush(NULL);
  clGetEventProfilingInfo((cl_event )chosen_platform,( cl_profiling_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetEventProfilingInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("45  : %s (expected)\n", "clGetEventProfilingInfo");
#endif
  fflush(NULL);
  clFlush((cl_command_queue)chosen_platform);
  printf("%s\n", "clFlush");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("46  : %s (expected)\n", "clFlush");
#endif
  fflush(NULL);
  clFinish((cl_command_queue)chosen_platform);
  printf("%s\n", "clFinish");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("47  : %s (expected)\n", "clFinish");
#endif
  fflush(NULL);
  clEnqueueReadBuffer((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( size_t )0,( size_t )0,( void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueReadBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("48  : %s (expected)\n", "clEnqueueReadBuffer");
#endif
  fflush(NULL);
  clEnqueueWriteBuffer((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( size_t )0,( size_t )0,( const void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueWriteBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("49  : %s (expected)\n", "clEnqueueWriteBuffer");
#endif
  fflush(NULL);
  clEnqueueCopyBuffer((cl_command_queue )chosen_platform,( cl_mem )0,( cl_mem )0,( size_t )0,( size_t )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueCopyBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("50  : %s (expected)\n", "clEnqueueCopyBuffer");
#endif
  fflush(NULL);
  clEnqueueReadImage((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( const size_t * )0,( const size_t * )0,( size_t )0,( size_t )0,( void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueReadImage");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("51  : %s (expected)\n", "clEnqueueReadImage");
#endif
  fflush(NULL);
  clEnqueueWriteImage((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( const size_t * )0,( const size_t * )0,( size_t )0,( size_t )0,( const void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueWriteImage");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("52  : %s (expected)\n", "clEnqueueWriteImage");
#endif
  fflush(NULL);
  clEnqueueCopyImage((cl_command_queue )chosen_platform,( cl_mem )0,( cl_mem )0,( const size_t * )0,( const size_t * )0,( const size_t * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueCopyImage");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("53  : %s (expected)\n", "clEnqueueCopyImage");
#endif
  fflush(NULL);
  clEnqueueCopyImageToBuffer((cl_command_queue )chosen_platform,( cl_mem )0,( cl_mem )0,( const size_t * )0,( const size_t * )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueCopyImageToBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("54  : %s (expected)\n", "clEnqueueCopyImageToBuffer");
#endif
  fflush(NULL);
  clEnqueueCopyBufferToImage((cl_command_queue )chosen_platform,( cl_mem )0,( cl_mem )0,( size_t )0,( const size_t * )0,( const size_t * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueCopyBufferToImage");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("55  : %s (expected)\n", "clEnqueueCopyBufferToImage");
#endif
  fflush(NULL);
  clEnqueueMapBuffer((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( cl_map_flags )0,( size_t )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event * )0,( cl_int *)0);
  printf("%s\n", "clEnqueueMapBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("56  : %s (expected)\n", "clEnqueueMapBuffer");
#endif
  fflush(NULL);
  clEnqueueMapImage((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( cl_map_flags )0,( const size_t * )0,( const size_t * )0,( size_t * )0,( size_t * )0,( cl_uint )0,( const cl_event * )0,( cl_event * )0,( cl_int *)0);
  printf("%s\n", "clEnqueueMapImage");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("57  : %s (expected)\n", "clEnqueueMapImage");
#endif
  fflush(NULL);
  clEnqueueUnmapMemObject((cl_command_queue )chosen_platform,( cl_mem )0,( void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueUnmapMemObject");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("58  : %s (expected)\n", "clEnqueueUnmapMemObject");
#endif
  fflush(NULL);
  clEnqueueNDRangeKernel((cl_command_queue )chosen_platform,( cl_kernel )0,( cl_uint )0,( const size_t * )0,( const size_t * )0,( const size_t * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueNDRangeKernel");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("59  : %s (expected)\n", "clEnqueueNDRangeKernel");
#endif
  fflush(NULL);
  clEnqueueTask((cl_command_queue )chosen_platform,( cl_kernel )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueTask");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("60  : %s (expected)\n", "clEnqueueTask");
#endif
  fflush(NULL);
  clEnqueueNativeKernel((cl_command_queue )chosen_platform,( void (*)(void *))0,( void * )0,( size_t )0,( cl_uint )0,( const cl_mem * )0,( const void ** )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueNativeKernel");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("61  : %s (expected)\n", "clEnqueueNativeKernel");
#endif
  fflush(NULL);
  clEnqueueMarker((cl_command_queue )chosen_platform,( cl_event *)0);
  printf("%s\n", "clEnqueueMarker");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("62  : %s (expected)\n", "clEnqueueMarker");
#endif
  fflush(NULL);
  clEnqueueWaitForEvents((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_event *)0);
  printf("%s\n", "clEnqueueWaitForEvents");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("63  : %s (expected)\n", "clEnqueueWaitForEvents");
#endif
  fflush(NULL);
  clEnqueueBarrier((cl_command_queue)chosen_platform);
  printf("%s\n", "clEnqueueBarrier");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("64  : %s (expected)\n", "clEnqueueBarrier");
#endif
  fflush(NULL);
  clGetExtensionFunctionAddress("extLIG");
  printf("%s\n", "clGetExtensionFunctionAddress");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("65  : %s (expected)\n", "clGetExtensionFunctionAddress");
#endif
  fflush(NULL);
  clCreateFromGLBuffer((cl_context )chosen_platform,( cl_mem_flags )0,( cl_GLuint )0,( int *)0);
  printf("%s\n", "clCreateFromGLBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("66  : %s (expected)\n", "clCreateFromGLBuffer");
#endif
  fflush(NULL);
  clCreateFromGLTexture2D((cl_context )chosen_platform,( cl_mem_flags )0,( cl_GLenum )0,( cl_GLint )0,( cl_GLuint )0,( cl_int *)0);
  printf("%s\n", "clCreateFromGLTexture2D");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("67  : %s (expected)\n", "clCreateFromGLTexture2D");
#endif
  fflush(NULL);
  clCreateFromGLTexture3D((cl_context )chosen_platform,( cl_mem_flags )0,( cl_GLenum )0,( cl_GLint )0,( cl_GLuint )0,( cl_int *)0);
  printf("%s\n", "clCreateFromGLTexture3D");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("68  : %s (expected)\n", "clCreateFromGLTexture3D");
#endif
  fflush(NULL);
  clCreateFromGLRenderbuffer((cl_context )chosen_platform,( cl_mem_flags )0,( cl_GLuint )0,( cl_int *)0);
  printf("%s\n", "clCreateFromGLRenderbuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("69  : %s (expected)\n", "clCreateFromGLRenderbuffer");
#endif
  fflush(NULL);
  clGetGLObjectInfo((cl_mem )chosen_platform,( cl_gl_object_type * )0,( cl_GLuint *)0);
  printf("%s\n", "clGetGLObjectInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("70  : %s (expected)\n", "clGetGLObjectInfo");
#endif
  fflush(NULL);
  clGetGLTextureInfo((cl_mem )chosen_platform,( cl_gl_texture_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetGLTextureInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("71  : %s (expected)\n", "clGetGLTextureInfo");
#endif
  fflush(NULL);
  clEnqueueAcquireGLObjects((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_mem * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueAcquireGLObjects");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("72  : %s (expected)\n", "clEnqueueAcquireGLObjects");
#endif
  fflush(NULL);
  clEnqueueReleaseGLObjects((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_mem * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueReleaseGLObjects");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("73  : %s (expected)\n", "clEnqueueReleaseGLObjects");
#endif
  fflush(NULL);
  clGetGLContextInfoKHR(properties,CL_CURRENT_DEVICE_FOR_GL_CONTEXT_KHR, 0, NULL, NULL);
  printf("%s\n", "clGetGLContextInfoKHR");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("74  : %s (expected)\n", "clGetGLContextInfoKHR");
#endif
  fflush(NULL);
  clSetEventCallback((cl_event )chosen_platform,( cl_int )0,( void (CL_CALLBACK * )(cl_event, cl_int, void *))0,( void *)0);
  printf("%s\n", "clSetEventCallback");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("81  : %s (expected)\n", "clSetEventCallback");
#endif
  fflush(NULL);
  clCreateSubBuffer((cl_mem )chosen_platform,( cl_mem_flags )0,( cl_buffer_create_type )0,( const void * )0,( cl_int *)0);
  printf("%s\n", "clCreateSubBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("82  : %s (expected)\n", "clCreateSubBuffer");
#endif
  fflush(NULL);
  clSetMemObjectDestructorCallback((cl_mem )chosen_platform,( void (CL_CALLBACK * )( cl_mem , void* ))0,( void *)0);
  printf("%s\n", "clSetMemObjectDestructorCallback");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("83  : %s (expected)\n", "clSetMemObjectDestructorCallback");
#endif
  fflush(NULL);
  clCreateUserEvent((cl_context )chosen_platform,( cl_int *)0);
  printf("%s\n", "clCreateUserEvent");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("84  : %s (expected)\n", "clCreateUserEvent");
#endif
  fflush(NULL);
  clSetUserEventStatus((cl_event )chosen_platform,( cl_int)0);
  printf("%s\n", "clSetUserEventStatus");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("85  : %s (expected)\n", "clSetUserEventStatus");
#endif
  fflush(NULL);
  clEnqueueReadBufferRect((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( const size_t * )0,( const size_t * )0,( const size_t * )0,( size_t )0,( size_t )0,( size_t )0,( size_t )0,( void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueReadBufferRect");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("86  : %s (expected)\n", "clEnqueueReadBufferRect");
#endif
  fflush(NULL);
  clEnqueueWriteBufferRect((cl_command_queue )chosen_platform,( cl_mem )0,( cl_bool )0,( const size_t * )0,( const size_t * )0,( const size_t * )0,( size_t )0,( size_t )0,( size_t )0,( size_t )0,( const void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueWriteBufferRect");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("87  : %s (expected)\n", "clEnqueueWriteBufferRect");
#endif
  fflush(NULL);
  clEnqueueCopyBufferRect((cl_command_queue )chosen_platform,( cl_mem )0,( cl_mem )0,( const size_t * )0,( const size_t * )0,( const size_t * )0,( size_t )0,( size_t )0,( size_t )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueCopyBufferRect");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("88  : %s (expected)\n", "clEnqueueCopyBufferRect");
#endif
  fflush(NULL);
  clCreateSubDevicesEXT((cl_device_id )chosen_platform,( const cl_device_partition_property_ext * )0,( cl_uint )0,( cl_device_id * )0,( cl_uint *)0);
  printf("%s\n", "clCreateSubDevicesEXT");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("89  : %s (expected)\n", "clCreateSubDevicesEXT");
#endif
  fflush(NULL);
  clRetainDeviceEXT((cl_device_id)chosen_platform);
  printf("%s\n", "clRetainDeviceEXT");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("90  : %s (expected)\n", "clRetainDeviceEXT");
#endif
  fflush(NULL);
  clReleaseDeviceEXT((cl_device_id)chosen_platform);
  printf("%s\n", "clReleaseDeviceEXT");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("91  : %s (expected)\n", "clReleaseDeviceEXT");
#endif
  fflush(NULL);
  clCreateEventFromGLsyncKHR((cl_context )chosen_platform,( cl_GLsync )0,( cl_int *)0);
  printf("%s\n", "clCreateEventFromGLsyncKHR");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("92  : %s (expected)\n", "clCreateEventFromGLsyncKHR");
#endif
  fflush(NULL);
  clCreateSubDevices((cl_device_id )chosen_platform,( const cl_device_partition_property * )0,( cl_uint )0,( cl_device_id * )0,( cl_uint *)0);
  printf("%s\n", "clCreateSubDevices");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("93  : %s (expected)\n", "clCreateSubDevices");
#endif
  fflush(NULL);
  clRetainDevice((cl_device_id)chosen_platform);
  printf("%s\n", "clRetainDevice");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("94  : %s (expected)\n", "clRetainDevice");
#endif
  fflush(NULL);
  clReleaseDevice((cl_device_id)chosen_platform);
  printf("%s\n", "clReleaseDevice");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("95  : %s (expected)\n", "clReleaseDevice");
#endif
  fflush(NULL);
  clCreateImage((cl_context )chosen_platform,( cl_mem_flags )0,( const cl_image_format * )0,( const cl_image_desc * )0,( void * )0,( cl_int *)0);
  printf("%s\n", "clCreateImage");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("96  : %s (expected)\n", "clCreateImage");
#endif
  fflush(NULL);
  clCreateProgramWithBuiltInKernels((cl_context )chosen_platform,( cl_uint )0,( const cl_device_id * )0,( const char * )0,( cl_int *)0);
  printf("%s\n", "clCreateProgramWithBuiltInKernels");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("97  : %s (expected)\n", "clCreateProgramWithBuiltInKernels");
#endif
  fflush(NULL);
  clCompileProgram((cl_program )chosen_platform,( cl_uint )0,( const cl_device_id * )0,( const char * )0,( cl_uint )0,( const cl_program * )0,( const char ** )0,( void (CL_CALLBACK * )(cl_program , void * ))0,( void *)0);
  printf("%s\n", "clCompileProgram");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("98  : %s (expected)\n", "clCompileProgram");
#endif
  fflush(NULL);
  clLinkProgram((cl_context )chosen_platform,( cl_uint )0,( const cl_device_id * )0,( const char * )0,( cl_uint )0,( const cl_program * )0,( void (CL_CALLBACK * )(cl_program , void * ))0,( void * )0,( cl_int *)0);
  printf("%s\n", "clLinkProgram");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("99  : %s (expected)\n", "clLinkProgram");
#endif
  fflush(NULL);
  clUnloadPlatformCompiler((cl_platform_id)chosen_platform);
  printf("%s\n", "clUnloadPlatformCompiler");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("100  : %s (expected)\n", "clUnloadPlatformCompiler");
#endif
  fflush(NULL);
  clGetKernelArgInfo((cl_kernel )chosen_platform,( cl_uint )0,( cl_kernel_arg_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetKernelArgInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("101  : %s (expected)\n", "clGetKernelArgInfo");
#endif
  fflush(NULL);
  clEnqueueFillBuffer((cl_command_queue )chosen_platform,( cl_mem )0,( const void * )0,( size_t )0,( size_t )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueFillBuffer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("102  : %s (expected)\n", "clEnqueueFillBuffer");
#endif
  fflush(NULL);
  clEnqueueFillImage((cl_command_queue )chosen_platform,( cl_mem )0,( const void * )0,( const size_t * )0,( const size_t * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueFillImage");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("103  : %s (expected)\n", "clEnqueueFillImage");
#endif
  fflush(NULL);
  clEnqueueMigrateMemObjects((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_mem * )0,( cl_mem_migration_flags )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueMigrateMemObjects");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("104  : %s (expected)\n", "clEnqueueMigrateMemObjects");
#endif
  fflush(NULL);
  clEnqueueMarkerWithWaitList((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueMarkerWithWaitList");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("105  : %s (expected)\n", "clEnqueueMarkerWithWaitList");
#endif
  fflush(NULL);
  clEnqueueBarrierWithWaitList((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueBarrierWithWaitList");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("106  : %s (expected)\n", "clEnqueueBarrierWithWaitList");
#endif
  fflush(NULL);
  clGetExtensionFunctionAddressForPlatform((cl_platform_id )chosen_platform,"extLIG");
  printf("%s\n", "clGetExtensionFunctionAddressForPlatform");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("107  : %s (expected)\n", "clGetExtensionFunctionAddressForPlatform");
#endif
  fflush(NULL);
  clCreateFromGLTexture((cl_context )chosen_platform,( cl_mem_flags )0,( cl_GLenum )0,( cl_GLint )0,( cl_GLuint )0,( cl_int *)0);
  printf("%s\n", "clCreateFromGLTexture");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("108  : %s (expected)\n", "clCreateFromGLTexture");
#endif
  fflush(NULL);
  clCreateFromEGLImageKHR((cl_context )chosen_platform,( CLeglDisplayKHR )0,( CLeglImageKHR )0,( cl_mem_flags )0,( const cl_egl_image_properties_khr * )0,( cl_int *)0);
  printf("%s\n", "clCreateFromEGLImageKHR");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("119  : %s (expected)\n", "clCreateFromEGLImageKHR");
#endif
  fflush(NULL);
  clEnqueueAcquireEGLObjectsKHR((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_mem * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueAcquireEGLObjectsKHR");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("120  : %s (expected)\n", "clEnqueueAcquireEGLObjectsKHR");
#endif
  fflush(NULL);
  clEnqueueReleaseEGLObjectsKHR((cl_command_queue )chosen_platform,( cl_uint )0,( const cl_mem * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueReleaseEGLObjectsKHR");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("121  : %s (expected)\n", "clEnqueueReleaseEGLObjectsKHR");
#endif
  fflush(NULL);
  clCreateEventFromEGLSyncKHR((cl_context )chosen_platform,( CLeglSyncKHR )0,( CLeglDisplayKHR )0,( cl_int *)0);
  printf("%s\n", "clCreateEventFromEGLSyncKHR");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("122  : %s (expected)\n", "clCreateEventFromEGLSyncKHR");
#endif
  fflush(NULL);
  clCreateCommandQueueWithProperties((cl_context )chosen_platform,( cl_device_id )0,( const cl_queue_properties * )0,( cl_int *)0);
  printf("%s\n", "clCreateCommandQueueWithProperties");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("123  : %s (expected)\n", "clCreateCommandQueueWithProperties");
#endif
  fflush(NULL);
  clCreatePipe((cl_context )chosen_platform,( cl_mem_flags )0,( cl_uint )0,( cl_uint )0,( const cl_pipe_properties * )0,( cl_int *)0);
  printf("%s\n", "clCreatePipe");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("124  : %s (expected)\n", "clCreatePipe");
#endif
  fflush(NULL);
  clGetPipeInfo((cl_mem )chosen_platform,( cl_pipe_info )0,( size_t )0,( void * )0,( size_t *)0);
  printf("%s\n", "clGetPipeInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("125  : %s (expected)\n", "clGetPipeInfo");
#endif
  fflush(NULL);
  clSVMAlloc((cl_context )chosen_platform,( cl_svm_mem_flags )0,( size_t )0,( cl_uint)0);
  printf("%s\n", "clSVMAlloc");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("126  : %s (expected)\n", "clSVMAlloc");
#endif
  fflush(NULL);
  clSVMFree((cl_context )chosen_platform,( void *)0);
  printf("%s\n", "clSVMFree");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("127  : %s (expected)\n", "clSVMFree");
#endif
  fflush(NULL);
  clEnqueueSVMFree((cl_command_queue )chosen_platform,( cl_uint )0,( void ** )0,( void (CL_CALLBACK * )(cl_command_queue , cl_uint , void ** , void * ))0,( void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueSVMFree");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("128  : %s (expected)\n", "clEnqueueSVMFree");
#endif
  fflush(NULL);
  clEnqueueSVMMemcpy((cl_command_queue )chosen_platform,( cl_bool )0,( void * )0,( const void * )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueSVMMemcpy");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("129  : %s (expected)\n", "clEnqueueSVMMemcpy");
#endif
  fflush(NULL);
  clEnqueueSVMMemFill((cl_command_queue )chosen_platform,( void * )0,( const void * )0,( size_t )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueSVMMemFill");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("130  : %s (expected)\n", "clEnqueueSVMMemFill");
#endif
  fflush(NULL);
  clEnqueueSVMMap((cl_command_queue )chosen_platform,( cl_bool )0,( cl_map_flags )0,( void * )0,( size_t )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueSVMMap");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("131  : %s (expected)\n", "clEnqueueSVMMap");
#endif
  fflush(NULL);
  clEnqueueSVMUnmap((cl_command_queue )chosen_platform,( void * )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueSVMUnmap");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("132  : %s (expected)\n", "clEnqueueSVMUnmap");
#endif
  fflush(NULL);
  clCreateSamplerWithProperties((cl_context )chosen_platform,( const cl_sampler_properties * )0,( cl_int *)0);
  printf("%s\n", "clCreateSamplerWithProperties");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("133  : %s (expected)\n", "clCreateSamplerWithProperties");
#endif
  fflush(NULL);
  clSetKernelArgSVMPointer((cl_kernel )chosen_platform,( cl_uint )0,( const void *)0);
  printf("%s\n", "clSetKernelArgSVMPointer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("134  : %s (expected)\n", "clSetKernelArgSVMPointer");
#endif
  fflush(NULL);
  clSetKernelExecInfo((cl_kernel )chosen_platform,( cl_kernel_exec_info )0,( size_t )0,( const void *)0);
  printf("%s\n", "clSetKernelExecInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("135  : %s (expected)\n", "clSetKernelExecInfo");
#endif
  fflush(NULL);
  clGetKernelSubGroupInfoKHR((cl_kernel )chosen_platform,( cl_device_id )0,( cl_kernel_sub_group_info )0,( size_t )0,( const void * )0,( size_t )0,( void* )0,( size_t*)0);
  printf("%s\n", "clGetKernelSubGroupInfoKHR");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("136  : %s (expected)\n", "clGetKernelSubGroupInfoKHR");
#endif
  fflush(NULL);
  clCloneKernel((cl_kernel )chosen_platform,( cl_int*)0);
  printf("%s\n", "clCloneKernel");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("137  : %s (expected)\n", "clCloneKernel");
#endif
  fflush(NULL);
  clCreateProgramWithIL((cl_context )chosen_platform,( const void* )0,( size_t )0,( cl_int*)0);
  printf("%s\n", "clCreateProgramWithIL");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("138  : %s (expected)\n", "clCreateProgramWithIL");
#endif
  fflush(NULL);
  clEnqueueSVMMigrateMem((cl_command_queue )chosen_platform,( cl_uint )0,( const void ** )0,( const size_t * )0,( cl_mem_migration_flags )0,( cl_uint )0,( const cl_event * )0,( cl_event *)0);
  printf("%s\n", "clEnqueueSVMMigrateMem");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("139  : %s (expected)\n", "clEnqueueSVMMigrateMem");
#endif
  fflush(NULL);
  clGetDeviceAndHostTimer((cl_device_id )chosen_platform,( cl_ulong* )0,( cl_ulong*)0);
  printf("%s\n", "clGetDeviceAndHostTimer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("140  : %s (expected)\n", "clGetDeviceAndHostTimer");
#endif
  fflush(NULL);
  clGetHostTimer((cl_device_id )chosen_platform,( cl_ulong *)0);
  printf("%s\n", "clGetHostTimer");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("141  : %s (expected)\n", "clGetHostTimer");
#endif
  fflush(NULL);
  clGetKernelSubGroupInfo((cl_kernel )chosen_platform,( cl_device_id )0,( cl_kernel_sub_group_info )0,( size_t )0,( const void* )0,( size_t )0,( void* )0,( size_t*)0);
  printf("%s\n", "clGetKernelSubGroupInfo");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("142  : %s (expected)\n", "clGetKernelSubGroupInfo");
#endif
  fflush(NULL);
  clSetDefaultDeviceCommandQueue((cl_context )chosen_platform,( cl_device_id )0,( cl_command_queue)0);
  printf("%s\n", "clSetDefaultDeviceCommandQueue");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("143  : %s (expected)\n", "clSetDefaultDeviceCommandQueue");
#endif
  fflush(NULL);
  clSetProgramReleaseCallback((cl_program )chosen_platform,( void (CL_CALLBACK * )(cl_program , void * ))0,( void *)0);
  printf("%s\n", "clSetProgramReleaseCallback");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("144  : %s (expected)\n", "clSetProgramReleaseCallback");
#endif
  fflush(NULL);
  clSetProgramSpecializationConstant((cl_program )chosen_platform,( cl_uint )0,( size_t )0,( const void*)0);
  printf("%s\n", "clSetProgramSpecializationConstant");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("145  : %s (expected)\n", "clSetProgramSpecializationConstant");
#endif
  fflush(NULL);
  clCreateBufferWithProperties((cl_context )chosen_platform,( const cl_mem_properties * )0,( cl_mem_flags )0,( size_t )0,( void * )0,( cl_int *)0);
  printf("%s\n", "clCreateBufferWithProperties");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("146  : %s (expected)\n", "clCreateBufferWithProperties");
#endif
  fflush(NULL);
  clCreateImageWithProperties((cl_context )chosen_platform,( const cl_mem_properties * )0,( cl_mem_flags )0,( const cl_image_format * )0,( const cl_image_desc * )0,( void * )0,( cl_int *)0);
  printf("%s\n", "clCreateImageWithProperties");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("147  : %s (expected)\n", "clCreateImageWithProperties");
#endif
  fflush(NULL);
  clSetContextDestructorCallback((cl_context )chosen_platform,( void (CL_CALLBACK * )(cl_context , void* ))0,( void *)0);
  printf("%s\n", "clSetContextDestructorCallback");
#ifdef OCL_ICD_PRINT_EXPECTED
  printf("148  : %s (expected)\n", "clSetContextDestructorCallback");
#endif
  fflush(NULL);
  return;
}
