/**
Copyright (c) 2012-2020, Brice Videau <bvideau@anl.gov>
Copyright (c) 2012-2020, Vincent Danjean <Vincent.Danjean@ens-lyon.org>
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Do not edit this file. It is automatically generated.

*/
#define _GNU_SOURCE 1
#include <stdio.h>
#include <dlfcn.h>

#pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wcpp"
#  define CL_USE_DEPRECATED_OPENCL_1_0_APIS
#  define CL_USE_DEPRECATED_OPENCL_1_1_APIS
#  define CL_USE_DEPRECATED_OPENCL_1_2_APIS
#  define CL_USE_DEPRECATED_OPENCL_2_0_APIS
#  define CL_USE_DEPRECATED_OPENCL_2_1_APIS
#  define CL_USE_DEPRECATED_OPENCL_2_2_APIS
#  define CL_TARGET_OPENCL_VERSION 300
#  include <CL/opencl.h>
#include <CL/cl.h>
#include <CL/cl_gl.h>
#include <CL/cl_egl.h>
#include <CL/cl_ext.h>
#pragma GCC diagnostic pop
CL_API_ENTRY cl_int CL_API_CALL
clGetDeviceIDs(cl_platform_id    platform ,
               cl_device_type    device_type , 
               cl_uint           num_entries , 
               cl_device_id *    devices , 
               cl_uint *         num_devices ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetDeviceIDs");
  if(p) {
    return((*(typeof(clGetDeviceIDs)*)p)(platform, device_type, num_entries, devices, num_devices));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetDeviceInfo(cl_device_id     device ,
                cl_device_info   param_name , 
                size_t           param_value_size , 
                void *           param_value ,
                size_t *         param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetDeviceInfo");
  if(p) {
    return((*(typeof(clGetDeviceInfo)*)p)(device, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainContext(cl_context  context ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainContext");
  if(p) {
    return((*(typeof(clRetainContext)*)p)(context));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseContext(cl_context  context ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseContext");
  if(p) {
    return((*(typeof(clReleaseContext)*)p)(context));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetContextInfo(cl_context          context , 
                 cl_context_info     param_name , 
                 size_t              param_value_size , 
                 void *              param_value , 
                 size_t *            param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetContextInfo");
  if(p) {
    return((*(typeof(clGetContextInfo)*)p)(context, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_command_queue CL_API_CALL
clCreateCommandQueue(cl_context                      context , 
                     cl_device_id                    device , 
                     cl_command_queue_properties     properties ,
                     cl_int *                        errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateCommandQueue");
  if(p) {
    return((*(typeof(clCreateCommandQueue)*)p)(context, device, properties, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_command_queue)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainCommandQueue(cl_command_queue  command_queue ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainCommandQueue");
  if(p) {
    return((*(typeof(clRetainCommandQueue)*)p)(command_queue));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseCommandQueue(cl_command_queue  command_queue ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseCommandQueue");
  if(p) {
    return((*(typeof(clReleaseCommandQueue)*)p)(command_queue));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetCommandQueueInfo(cl_command_queue       command_queue ,
                      cl_command_queue_info  param_name ,
                      size_t                 param_value_size ,
                      void *                 param_value ,
                      size_t *               param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetCommandQueueInfo");
  if(p) {
    return((*(typeof(clGetCommandQueueInfo)*)p)(command_queue, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetCommandQueueProperty(cl_command_queue               command_queue ,
                          cl_command_queue_properties    properties , 
                          cl_bool                         enable ,
                          cl_command_queue_properties *  old_properties ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetCommandQueueProperty");
  if(p) {
    return((*(typeof(clSetCommandQueueProperty)*)p)(command_queue, properties, enable, old_properties));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateBuffer(cl_context    context ,
               cl_mem_flags  flags ,
               size_t        size ,
               void *        host_ptr ,
               cl_int *      errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateBuffer");
  if(p) {
    return((*(typeof(clCreateBuffer)*)p)(context, flags, size, host_ptr, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateImage2D(cl_context               context ,
                cl_mem_flags             flags ,
                const cl_image_format *  image_format ,
                size_t                   image_width ,
                size_t                   image_height ,
                size_t                   image_row_pitch , 
                void *                   host_ptr ,
                cl_int *                 errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateImage2D");
  if(p) {
    return((*(typeof(clCreateImage2D)*)p)(context, flags, image_format, image_width, image_height, image_row_pitch, host_ptr, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateImage3D(cl_context               context ,
                cl_mem_flags             flags ,
                const cl_image_format *  image_format ,
                size_t                   image_width , 
                size_t                   image_height ,
                size_t                   image_depth , 
                size_t                   image_row_pitch , 
                size_t                   image_slice_pitch , 
                void *                   host_ptr ,
                cl_int *                 errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateImage3D");
  if(p) {
    return((*(typeof(clCreateImage3D)*)p)(context, flags, image_format, image_width, image_height, image_depth, image_row_pitch, image_slice_pitch, host_ptr, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainMemObject(cl_mem  memobj ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainMemObject");
  if(p) {
    return((*(typeof(clRetainMemObject)*)p)(memobj));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseMemObject(cl_mem  memobj ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseMemObject");
  if(p) {
    return((*(typeof(clReleaseMemObject)*)p)(memobj));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetSupportedImageFormats(cl_context            context ,
                           cl_mem_flags          flags ,
                           cl_mem_object_type    image_type ,
                           cl_uint               num_entries ,
                           cl_image_format *     image_formats ,
                           cl_uint *             num_image_formats ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetSupportedImageFormats");
  if(p) {
    return((*(typeof(clGetSupportedImageFormats)*)p)(context, flags, image_type, num_entries, image_formats, num_image_formats));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetMemObjectInfo(cl_mem            memobj ,
                   cl_mem_info       param_name , 
                   size_t            param_value_size ,
                   void *            param_value ,
                   size_t *          param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetMemObjectInfo");
  if(p) {
    return((*(typeof(clGetMemObjectInfo)*)p)(memobj, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetImageInfo(cl_mem            image ,
               cl_image_info     param_name , 
               size_t            param_value_size ,
               void *            param_value ,
               size_t *          param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetImageInfo");
  if(p) {
    return((*(typeof(clGetImageInfo)*)p)(image, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_sampler CL_API_CALL
clCreateSampler(cl_context           context ,
                cl_bool              normalized_coords , 
                cl_addressing_mode   addressing_mode , 
                cl_filter_mode       filter_mode ,
                cl_int *             errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateSampler");
  if(p) {
    return((*(typeof(clCreateSampler)*)p)(context, normalized_coords, addressing_mode, filter_mode, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_sampler)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainSampler(cl_sampler  sampler ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainSampler");
  if(p) {
    return((*(typeof(clRetainSampler)*)p)(sampler));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseSampler(cl_sampler  sampler ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseSampler");
  if(p) {
    return((*(typeof(clReleaseSampler)*)p)(sampler));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetSamplerInfo(cl_sampler          sampler ,
                 cl_sampler_info     param_name ,
                 size_t              param_value_size ,
                 void *              param_value ,
                 size_t *            param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetSamplerInfo");
  if(p) {
    return((*(typeof(clGetSamplerInfo)*)p)(sampler, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithSource(cl_context         context ,
                          cl_uint            count ,
                          const char **      strings ,
                          const size_t *     lengths ,
                          cl_int *           errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateProgramWithSource");
  if(p) {
    return((*(typeof(clCreateProgramWithSource)*)p)(context, count, strings, lengths, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_program)0;
  }
}

CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithBinary(cl_context                      context ,
                          cl_uint                         num_devices ,
                          const cl_device_id *            device_list ,
                          const size_t *                  lengths ,
                          const unsigned char **          binaries ,
                          cl_int *                        binary_status ,
                          cl_int *                        errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateProgramWithBinary");
  if(p) {
    return((*(typeof(clCreateProgramWithBinary)*)p)(context, num_devices, device_list, lengths, binaries, binary_status, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_program)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainProgram(cl_program  program ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainProgram");
  if(p) {
    return((*(typeof(clRetainProgram)*)p)(program));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseProgram(cl_program  program ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseProgram");
  if(p) {
    return((*(typeof(clReleaseProgram)*)p)(program));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clBuildProgram(cl_program            program ,
               cl_uint               num_devices ,
               const cl_device_id *  device_list ,
               const char *          options , 
               void (CL_CALLBACK *   pfn_notify )(cl_program  program , void *  user_data ),
               void *                user_data ){
  void (*p)()=dlsym(RTLD_NEXT, "clBuildProgram");
  if(p) {
    return((*(typeof(clBuildProgram)*)p)(program, num_devices, device_list, options, pfn_notify, user_data));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetProgramInfo(cl_program          program ,
                 cl_program_info     param_name ,
                 size_t              param_value_size ,
                 void *              param_value ,
                 size_t *            param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetProgramInfo");
  if(p) {
    return((*(typeof(clGetProgramInfo)*)p)(program, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetProgramBuildInfo(cl_program             program ,
                      cl_device_id           device ,
                      cl_program_build_info  param_name ,
                      size_t                 param_value_size ,
                      void *                 param_value ,
                      size_t *               param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetProgramBuildInfo");
  if(p) {
    return((*(typeof(clGetProgramBuildInfo)*)p)(program, device, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_kernel CL_API_CALL
clCreateKernel(cl_program       program ,
               const char *     kernel_name ,
               cl_int *         errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateKernel");
  if(p) {
    return((*(typeof(clCreateKernel)*)p)(program, kernel_name, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_kernel)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clCreateKernelsInProgram(cl_program      program ,
                         cl_uint         num_kernels ,
                         cl_kernel *     kernels ,
                         cl_uint *       num_kernels_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateKernelsInProgram");
  if(p) {
    return((*(typeof(clCreateKernelsInProgram)*)p)(program, num_kernels, kernels, num_kernels_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainKernel(cl_kernel     kernel ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainKernel");
  if(p) {
    return((*(typeof(clRetainKernel)*)p)(kernel));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseKernel(cl_kernel    kernel ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseKernel");
  if(p) {
    return((*(typeof(clReleaseKernel)*)p)(kernel));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetKernelArg(cl_kernel     kernel ,
               cl_uint       arg_index ,
               size_t        arg_size ,
               const void *  arg_value ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetKernelArg");
  if(p) {
    return((*(typeof(clSetKernelArg)*)p)(kernel, arg_index, arg_size, arg_value));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetKernelInfo(cl_kernel        kernel ,
                cl_kernel_info   param_name ,
                size_t           param_value_size ,
                void *           param_value ,
                size_t *         param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetKernelInfo");
  if(p) {
    return((*(typeof(clGetKernelInfo)*)p)(kernel, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetKernelWorkGroupInfo(cl_kernel                   kernel ,
                         cl_device_id                device ,
                         cl_kernel_work_group_info   param_name ,
                         size_t                      param_value_size ,
                         void *                      param_value ,
                         size_t *                    param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetKernelWorkGroupInfo");
  if(p) {
    return((*(typeof(clGetKernelWorkGroupInfo)*)p)(kernel, device, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetEventInfo(cl_event          event ,
               cl_event_info     param_name ,
               size_t            param_value_size ,
               void *            param_value ,
               size_t *          param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetEventInfo");
  if(p) {
    return((*(typeof(clGetEventInfo)*)p)(event, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainEvent(cl_event  event ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainEvent");
  if(p) {
    return((*(typeof(clRetainEvent)*)p)(event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseEvent(cl_event  event ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseEvent");
  if(p) {
    return((*(typeof(clReleaseEvent)*)p)(event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetEventProfilingInfo(cl_event             event ,
                        cl_profiling_info    param_name ,
                        size_t               param_value_size ,
                        void *               param_value ,
                        size_t *             param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetEventProfilingInfo");
  if(p) {
    return((*(typeof(clGetEventProfilingInfo)*)p)(event, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clFlush(cl_command_queue  command_queue ){
  void (*p)()=dlsym(RTLD_NEXT, "clFlush");
  if(p) {
    return((*(typeof(clFlush)*)p)(command_queue));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clFinish(cl_command_queue  command_queue ){
  void (*p)()=dlsym(RTLD_NEXT, "clFinish");
  if(p) {
    return((*(typeof(clFinish)*)p)(command_queue));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReadBuffer(cl_command_queue     command_queue ,
                    cl_mem               buffer ,
                    cl_bool              blocking_read ,
                    size_t               offset ,
                    size_t               cb , 
                    void *               ptr ,
                    cl_uint              num_events_in_wait_list ,
                    const cl_event *     event_wait_list ,
                    cl_event *           event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueReadBuffer");
  if(p) {
    return((*(typeof(clEnqueueReadBuffer)*)p)(command_queue, buffer, blocking_read, offset, cb, ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWriteBuffer(cl_command_queue    command_queue , 
                     cl_mem              buffer , 
                     cl_bool             blocking_write , 
                     size_t              offset , 
                     size_t              cb , 
                     const void *        ptr , 
                     cl_uint             num_events_in_wait_list , 
                     const cl_event *    event_wait_list , 
                     cl_event *          event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueWriteBuffer");
  if(p) {
    return((*(typeof(clEnqueueWriteBuffer)*)p)(command_queue, buffer, blocking_write, offset, cb, ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyBuffer(cl_command_queue     command_queue , 
                    cl_mem               src_buffer ,
                    cl_mem               dst_buffer , 
                    size_t               src_offset ,
                    size_t               dst_offset ,
                    size_t               cb , 
                    cl_uint              num_events_in_wait_list ,
                    const cl_event *     event_wait_list ,
                    cl_event *           event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueCopyBuffer");
  if(p) {
    return((*(typeof(clEnqueueCopyBuffer)*)p)(command_queue, src_buffer, dst_buffer, src_offset, dst_offset, cb, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReadImage(cl_command_queue      command_queue ,
                   cl_mem                image ,
                   cl_bool               blocking_read , 
                   const size_t *        origin ,
                   const size_t *        region ,
                   size_t                row_pitch ,
                   size_t                slice_pitch , 
                   void *                ptr ,
                   cl_uint               num_events_in_wait_list ,
                   const cl_event *      event_wait_list ,
                   cl_event *            event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueReadImage");
  if(p) {
    return((*(typeof(clEnqueueReadImage)*)p)(command_queue, image, blocking_read, origin, region, row_pitch, slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWriteImage(cl_command_queue     command_queue ,
                    cl_mem               image ,
                    cl_bool              blocking_write , 
                    const size_t *       origin ,
                    const size_t *       region ,
                    size_t               input_row_pitch ,
                    size_t               input_slice_pitch , 
                    const void *         ptr ,
                    cl_uint              num_events_in_wait_list ,
                    const cl_event *     event_wait_list ,
                    cl_event *           event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueWriteImage");
  if(p) {
    return((*(typeof(clEnqueueWriteImage)*)p)(command_queue, image, blocking_write, origin, region, input_row_pitch, input_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyImage(cl_command_queue      command_queue ,
                   cl_mem                src_image ,
                   cl_mem                dst_image , 
                   const size_t *        src_origin ,
                   const size_t *        dst_origin ,
                   const size_t *        region , 
                   cl_uint               num_events_in_wait_list ,
                   const cl_event *      event_wait_list ,
                   cl_event *            event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueCopyImage");
  if(p) {
    return((*(typeof(clEnqueueCopyImage)*)p)(command_queue, src_image, dst_image, src_origin, dst_origin, region, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyImageToBuffer(cl_command_queue  command_queue ,
                           cl_mem            src_image ,
                           cl_mem            dst_buffer , 
                           const size_t *    src_origin ,
                           const size_t *    region , 
                           size_t            dst_offset ,
                           cl_uint           num_events_in_wait_list ,
                           const cl_event *  event_wait_list ,
                           cl_event *        event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueCopyImageToBuffer");
  if(p) {
    return((*(typeof(clEnqueueCopyImageToBuffer)*)p)(command_queue, src_image, dst_buffer, src_origin, region, dst_offset, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyBufferToImage(cl_command_queue  command_queue ,
                           cl_mem            src_buffer ,
                           cl_mem            dst_image , 
                           size_t            src_offset ,
                           const size_t *    dst_origin ,
                           const size_t *    region , 
                           cl_uint           num_events_in_wait_list ,
                           const cl_event *  event_wait_list ,
                           cl_event *        event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueCopyBufferToImage");
  if(p) {
    return((*(typeof(clEnqueueCopyBufferToImage)*)p)(command_queue, src_buffer, dst_image, src_offset, dst_origin, region, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY void * CL_API_CALL
clEnqueueMapBuffer(cl_command_queue  command_queue ,
                   cl_mem            buffer ,
                   cl_bool           blocking_map , 
                   cl_map_flags      map_flags ,
                   size_t            offset ,
                   size_t            cb ,
                   cl_uint           num_events_in_wait_list ,
                   const cl_event *  event_wait_list ,
                   cl_event *        event ,
                   cl_int *          errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueMapBuffer");
  if(p) {
    return((*(typeof(clEnqueueMapBuffer)*)p)(command_queue, buffer, blocking_map, map_flags, offset, cb, num_events_in_wait_list, event_wait_list, event, errcode_ret));
  } else {
    printf("-1 : ");
    return (void *)0;
  }
}

CL_API_ENTRY void * CL_API_CALL
clEnqueueMapImage(cl_command_queue   command_queue ,
                  cl_mem             image , 
                  cl_bool            blocking_map , 
                  cl_map_flags       map_flags , 
                  const size_t *     origin ,
                  const size_t *     region ,
                  size_t *           image_row_pitch ,
                  size_t *           image_slice_pitch ,
                  cl_uint            num_events_in_wait_list ,
                  const cl_event *   event_wait_list ,
                  cl_event *         event ,
                  cl_int *           errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueMapImage");
  if(p) {
    return((*(typeof(clEnqueueMapImage)*)p)(command_queue, image, blocking_map, map_flags, origin, region, image_row_pitch, image_slice_pitch, num_events_in_wait_list, event_wait_list, event, errcode_ret));
  } else {
    printf("-1 : ");
    return (void *)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueUnmapMemObject(cl_command_queue  command_queue ,
                        cl_mem            memobj ,
                        void *            mapped_ptr ,
                        cl_uint           num_events_in_wait_list ,
                        const cl_event *   event_wait_list ,
                        cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueUnmapMemObject");
  if(p) {
    return((*(typeof(clEnqueueUnmapMemObject)*)p)(command_queue, memobj, mapped_ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueNDRangeKernel(cl_command_queue  command_queue ,
                       cl_kernel         kernel ,
                       cl_uint           work_dim ,
                       const size_t *    global_work_offset ,
                       const size_t *    global_work_size ,
                       const size_t *    local_work_size ,
                       cl_uint           num_events_in_wait_list ,
                       const cl_event *  event_wait_list ,
                       cl_event *        event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueNDRangeKernel");
  if(p) {
    return((*(typeof(clEnqueueNDRangeKernel)*)p)(command_queue, kernel, work_dim, global_work_offset, global_work_size, local_work_size, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueTask(cl_command_queue   command_queue ,
              cl_kernel          kernel ,
              cl_uint            num_events_in_wait_list ,
              const cl_event *   event_wait_list ,
              cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueTask");
  if(p) {
    return((*(typeof(clEnqueueTask)*)p)(command_queue, kernel, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueNativeKernel(cl_command_queue   command_queue ,
					  void (*user_func)(void *), 
                      void *             args ,
                      size_t             cb_args , 
                      cl_uint            num_mem_objects ,
                      const cl_mem *     mem_list ,
                      const void **      args_mem_loc ,
                      cl_uint            num_events_in_wait_list ,
                      const cl_event *   event_wait_list ,
                      cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueNativeKernel");
  if(p) {
    return((*(typeof(clEnqueueNativeKernel)*)p)(command_queue, user_func, args, cb_args, num_mem_objects, mem_list, args_mem_loc, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueMarker(cl_command_queue     command_queue ,
                cl_event *           event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueMarker");
  if(p) {
    return((*(typeof(clEnqueueMarker)*)p)(command_queue, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWaitForEvents(cl_command_queue  command_queue ,
                       cl_uint           num_events ,
                       const cl_event *  event_list ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueWaitForEvents");
  if(p) {
    return((*(typeof(clEnqueueWaitForEvents)*)p)(command_queue, num_events, event_list));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueBarrier(cl_command_queue  command_queue ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueBarrier");
  if(p) {
    return((*(typeof(clEnqueueBarrier)*)p)(command_queue));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLBuffer(cl_context      context ,
                     cl_mem_flags    flags ,
                     cl_GLuint       bufobj ,
                     int *           errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateFromGLBuffer");
  if(p) {
    return((*(typeof(clCreateFromGLBuffer)*)p)(context, flags, bufobj, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLTexture2D(cl_context       context ,
                        cl_mem_flags     flags ,
                        cl_GLenum        target ,
                        cl_GLint         miplevel ,
                        cl_GLuint        texture ,
                        cl_int *         errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateFromGLTexture2D");
  if(p) {
    return((*(typeof(clCreateFromGLTexture2D)*)p)(context, flags, target, miplevel, texture, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLTexture3D(cl_context       context ,
                        cl_mem_flags     flags ,
                        cl_GLenum        target ,
                        cl_GLint         miplevel ,
                        cl_GLuint        texture ,
                        cl_int *         errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateFromGLTexture3D");
  if(p) {
    return((*(typeof(clCreateFromGLTexture3D)*)p)(context, flags, target, miplevel, texture, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLRenderbuffer(cl_context    context ,
                           cl_mem_flags  flags ,
                           cl_GLuint     renderbuffer ,
                           cl_int *      errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateFromGLRenderbuffer");
  if(p) {
    return((*(typeof(clCreateFromGLRenderbuffer)*)p)(context, flags, renderbuffer, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetGLObjectInfo(cl_mem                 memobj ,
                  cl_gl_object_type *    gl_object_type ,
                  cl_GLuint *               gl_object_name ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetGLObjectInfo");
  if(p) {
    return((*(typeof(clGetGLObjectInfo)*)p)(memobj, gl_object_type, gl_object_name));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetGLTextureInfo(cl_mem                memobj ,
                   cl_gl_texture_info    param_name ,
                   size_t                param_value_size ,
                   void *                param_value ,
                   size_t *              param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetGLTextureInfo");
  if(p) {
    return((*(typeof(clGetGLTextureInfo)*)p)(memobj, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueAcquireGLObjects(cl_command_queue       command_queue ,
                          cl_uint                num_objects ,
                          const cl_mem *         mem_objects ,
                          cl_uint                num_events_in_wait_list ,
                          const cl_event *       event_wait_list ,
                          cl_event *             event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueAcquireGLObjects");
  if(p) {
    return((*(typeof(clEnqueueAcquireGLObjects)*)p)(command_queue, num_objects, mem_objects, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReleaseGLObjects(cl_command_queue       command_queue ,
                          cl_uint                num_objects ,
                          const cl_mem *         mem_objects ,
                          cl_uint                num_events_in_wait_list ,
                          const cl_event *       event_wait_list ,
                          cl_event *             event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueReleaseGLObjects");
  if(p) {
    return((*(typeof(clEnqueueReleaseGLObjects)*)p)(command_queue, num_objects, mem_objects, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetEventCallback(cl_event     event ,
                   cl_int       command_exec_callback_type ,
                   void (CL_CALLBACK *  pfn_notify )(cl_event, cl_int, void *),
                   void *       user_data ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetEventCallback");
  if(p) {
    return((*(typeof(clSetEventCallback)*)p)(event, command_exec_callback_type, pfn_notify, user_data));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateSubBuffer(cl_mem                    buffer ,
                  cl_mem_flags              flags ,
                  cl_buffer_create_type     buffer_create_type ,
                  const void *              buffer_create_info ,
                  cl_int *                  errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateSubBuffer");
  if(p) {
    return((*(typeof(clCreateSubBuffer)*)p)(buffer, flags, buffer_create_type, buffer_create_info, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetMemObjectDestructorCallback(cl_mem  memobj ,
                                 void (CL_CALLBACK * pfn_notify)( cl_mem  memobj , void* user_data),
                                 void * user_data  ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetMemObjectDestructorCallback");
  if(p) {
    return((*(typeof(clSetMemObjectDestructorCallback)*)p)(memobj, pfn_notify, user_data));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_event CL_API_CALL
clCreateUserEvent(cl_context     context ,
                  cl_int *       errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateUserEvent");
  if(p) {
    return((*(typeof(clCreateUserEvent)*)p)(context, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_event)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetUserEventStatus(cl_event    event ,
                     cl_int      execution_status ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetUserEventStatus");
  if(p) {
    return((*(typeof(clSetUserEventStatus)*)p)(event, execution_status));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReadBufferRect(cl_command_queue     command_queue ,
                        cl_mem               buffer ,
                        cl_bool              blocking_read ,
                        const size_t *       buffer_origin ,
                        const size_t *       host_origin , 
                        const size_t *       region ,
                        size_t               buffer_row_pitch ,
                        size_t               buffer_slice_pitch ,
                        size_t               host_row_pitch ,
                        size_t               host_slice_pitch ,                        
                        void *               ptr ,
                        cl_uint              num_events_in_wait_list ,
                        const cl_event *     event_wait_list ,
                        cl_event *           event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueReadBufferRect");
  if(p) {
    return((*(typeof(clEnqueueReadBufferRect)*)p)(command_queue, buffer, blocking_read, buffer_origin, host_origin, region, buffer_row_pitch, buffer_slice_pitch, host_row_pitch, host_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueWriteBufferRect(cl_command_queue     command_queue ,
                         cl_mem               buffer ,
                         cl_bool              blocking_write ,
                         const size_t *       buffer_origin ,
                         const size_t *       host_origin , 
                         const size_t *       region ,
                         size_t               buffer_row_pitch ,
                         size_t               buffer_slice_pitch ,
                         size_t               host_row_pitch ,
                         size_t               host_slice_pitch ,                        
                         const void *         ptr ,
                         cl_uint              num_events_in_wait_list ,
                         const cl_event *     event_wait_list ,
                         cl_event *           event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueWriteBufferRect");
  if(p) {
    return((*(typeof(clEnqueueWriteBufferRect)*)p)(command_queue, buffer, blocking_write, buffer_origin, host_origin, region, buffer_row_pitch, buffer_slice_pitch, host_row_pitch, host_slice_pitch, ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueCopyBufferRect(cl_command_queue     command_queue , 
                        cl_mem               src_buffer ,
                        cl_mem               dst_buffer , 
                        const size_t *       src_origin ,
                        const size_t *       dst_origin ,
                        const size_t *       region , 
                        size_t               src_row_pitch ,
                        size_t               src_slice_pitch ,
                        size_t               dst_row_pitch ,
                        size_t               dst_slice_pitch ,
                        cl_uint              num_events_in_wait_list ,
                        const cl_event *     event_wait_list ,
                        cl_event *           event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueCopyBufferRect");
  if(p) {
    return((*(typeof(clEnqueueCopyBufferRect)*)p)(command_queue, src_buffer, dst_buffer, src_origin, dst_origin, region, src_row_pitch, src_slice_pitch, dst_row_pitch, dst_slice_pitch, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clCreateSubDevicesEXT(cl_device_id in_device,
                      const cl_device_partition_property_ext *  properties ,
                      cl_uint num_entries,
                      cl_device_id * out_devices,
                      cl_uint * num_devices ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateSubDevicesEXT");
  if(p) {
    return((*(typeof(clCreateSubDevicesEXT)*)p)(in_device, properties, num_entries, out_devices, num_devices));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainDeviceEXT( cl_device_id device ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainDeviceEXT");
  if(p) {
    return((*(typeof(clRetainDeviceEXT)*)p)(device));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseDeviceEXT( cl_device_id device ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseDeviceEXT");
  if(p) {
    return((*(typeof(clReleaseDeviceEXT)*)p)(device));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_event CL_API_CALL
clCreateEventFromGLsyncKHR(cl_context            context ,
                           cl_GLsync             cl_GLsync ,
                           cl_int *              errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateEventFromGLsyncKHR");
  if(p) {
    return((*(typeof(clCreateEventFromGLsyncKHR)*)p)(context, cl_GLsync, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_event)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clCreateSubDevices(cl_device_id                          in_device ,
                   const cl_device_partition_property *  properties ,
                   cl_uint                               num_devices ,
                   cl_device_id *                        out_devices ,
                   cl_uint *                             num_devices_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateSubDevices");
  if(p) {
    return((*(typeof(clCreateSubDevices)*)p)(in_device, properties, num_devices, out_devices, num_devices_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clRetainDevice(cl_device_id  device ){
  void (*p)()=dlsym(RTLD_NEXT, "clRetainDevice");
  if(p) {
    return((*(typeof(clRetainDevice)*)p)(device));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clReleaseDevice(cl_device_id  device ){
  void (*p)()=dlsym(RTLD_NEXT, "clReleaseDevice");
  if(p) {
    return((*(typeof(clReleaseDevice)*)p)(device));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateImage(cl_context               context ,
              cl_mem_flags             flags ,
              const cl_image_format *  image_format ,
              const cl_image_desc *    image_desc , 
              void *                   host_ptr ,
              cl_int *                 errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateImage");
  if(p) {
    return((*(typeof(clCreateImage)*)p)(context, flags, image_format, image_desc, host_ptr, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithBuiltInKernels(cl_context             context ,
                                  cl_uint                num_devices ,
                                  const cl_device_id *   device_list ,
                                  const char *           kernel_names ,
                                  cl_int *               errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateProgramWithBuiltInKernels");
  if(p) {
    return((*(typeof(clCreateProgramWithBuiltInKernels)*)p)(context, num_devices, device_list, kernel_names, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_program)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clCompileProgram(cl_program            program ,
                 cl_uint               num_devices ,
                 const cl_device_id *  device_list ,
                 const char *          options , 
                 cl_uint               num_input_headers ,
                 const cl_program *    input_headers ,
                 const char **         header_include_names ,
                 void (CL_CALLBACK *   pfn_notify )(cl_program  program , void *  user_data ),
                 void *                user_data ){
  void (*p)()=dlsym(RTLD_NEXT, "clCompileProgram");
  if(p) {
    return((*(typeof(clCompileProgram)*)p)(program, num_devices, device_list, options, num_input_headers, input_headers, header_include_names, pfn_notify, user_data));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_program CL_API_CALL
clLinkProgram(cl_context            context ,
              cl_uint               num_devices ,
              const cl_device_id *  device_list ,
              const char *          options , 
              cl_uint               num_input_programs ,
              const cl_program *    input_programs ,
              void (CL_CALLBACK *   pfn_notify )(cl_program  program , void *  user_data ),
              void *                user_data ,
              cl_int *              errcode_ret  ){
  void (*p)()=dlsym(RTLD_NEXT, "clLinkProgram");
  if(p) {
    return((*(typeof(clLinkProgram)*)p)(context, num_devices, device_list, options, num_input_programs, input_programs, pfn_notify, user_data, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_program)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clUnloadPlatformCompiler(cl_platform_id  platform ){
  void (*p)()=dlsym(RTLD_NEXT, "clUnloadPlatformCompiler");
  if(p) {
    return((*(typeof(clUnloadPlatformCompiler)*)p)(platform));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetKernelArgInfo(cl_kernel        kernel ,
                   cl_uint          arg_indx ,
                   cl_kernel_arg_info   param_name ,
                   size_t           param_value_size ,
                   void *           param_value ,
                   size_t *         param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetKernelArgInfo");
  if(p) {
    return((*(typeof(clGetKernelArgInfo)*)p)(kernel, arg_indx, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueFillBuffer(cl_command_queue    command_queue ,
                    cl_mem              buffer , 
                    const void *        pattern , 
                    size_t              pattern_size , 
                    size_t              offset , 
                    size_t              size , 
                    cl_uint             num_events_in_wait_list , 
                    const cl_event *    event_wait_list , 
                    cl_event *          event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueFillBuffer");
  if(p) {
    return((*(typeof(clEnqueueFillBuffer)*)p)(command_queue, buffer, pattern, pattern_size, offset, size, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueFillImage(cl_command_queue    command_queue ,
                   cl_mem              image , 
                   const void *        fill_color , 
                   const size_t *      origin , 
                   const size_t *      region , 
                   cl_uint             num_events_in_wait_list , 
                   const cl_event *    event_wait_list , 
                   cl_event *          event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueFillImage");
  if(p) {
    return((*(typeof(clEnqueueFillImage)*)p)(command_queue, image, fill_color, origin, region, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueMigrateMemObjects(cl_command_queue        command_queue ,
                           cl_uint                 num_mem_objects ,
                           const cl_mem *          mem_objects ,
                           cl_mem_migration_flags  flags ,
                           cl_uint                 num_events_in_wait_list ,
                           const cl_event *        event_wait_list ,
                           cl_event *              event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueMigrateMemObjects");
  if(p) {
    return((*(typeof(clEnqueueMigrateMemObjects)*)p)(command_queue, num_mem_objects, mem_objects, flags, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueMarkerWithWaitList(cl_command_queue  command_queue ,
                            cl_uint            num_events_in_wait_list ,
                            const cl_event *   event_wait_list ,
                            cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueMarkerWithWaitList");
  if(p) {
    return((*(typeof(clEnqueueMarkerWithWaitList)*)p)(command_queue, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueBarrierWithWaitList(cl_command_queue  command_queue ,
                             cl_uint            num_events_in_wait_list ,
                             const cl_event *   event_wait_list ,
                             cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueBarrierWithWaitList");
  if(p) {
    return((*(typeof(clEnqueueBarrierWithWaitList)*)p)(command_queue, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY void * CL_API_CALL 
clGetExtensionFunctionAddressForPlatform(cl_platform_id  platform ,
                                         const char *    func_name ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetExtensionFunctionAddressForPlatform");
  if(p) {
    return((*(typeof(clGetExtensionFunctionAddressForPlatform)*)p)(platform, func_name));
  } else {
    printf("-1 : ");
    return (void *)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromGLTexture(cl_context       context ,
                      cl_mem_flags     flags ,
                      cl_GLenum        target ,
                      cl_GLint         miplevel ,
                      cl_GLuint        texture ,
                      cl_int *         errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateFromGLTexture");
  if(p) {
    return((*(typeof(clCreateFromGLTexture)*)p)(context, flags, target, miplevel, texture, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateFromEGLImageKHR(cl_context                   context ,
                        CLeglDisplayKHR              egldisplay ,
                        CLeglImageKHR                eglimage ,
                        cl_mem_flags                 flags ,
                        const cl_egl_image_properties_khr *  properties ,
                        cl_int *                     errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateFromEGLImageKHR");
  if(p) {
    return((*(typeof(clCreateFromEGLImageKHR)*)p)(context, egldisplay, eglimage, flags, properties, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueAcquireEGLObjectsKHR(cl_command_queue  command_queue ,
                              cl_uint           num_objects ,
                              const cl_mem *    mem_objects ,
                              cl_uint           num_events_in_wait_list ,
                              const cl_event *  event_wait_list ,
                              cl_event *        event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueAcquireEGLObjectsKHR");
  if(p) {
    return((*(typeof(clEnqueueAcquireEGLObjectsKHR)*)p)(command_queue, num_objects, mem_objects, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueReleaseEGLObjectsKHR(cl_command_queue  command_queue ,
                              cl_uint           num_objects ,
                              const cl_mem *    mem_objects ,
                              cl_uint           num_events_in_wait_list ,
                              const cl_event *  event_wait_list ,
                              cl_event *        event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueReleaseEGLObjectsKHR");
  if(p) {
    return((*(typeof(clEnqueueReleaseEGLObjectsKHR)*)p)(command_queue, num_objects, mem_objects, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_event CL_API_CALL
clCreateEventFromEGLSyncKHR(cl_context       context ,
                            CLeglSyncKHR     sync ,
                            CLeglDisplayKHR  display ,
                            cl_int *         errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateEventFromEGLSyncKHR");
  if(p) {
    return((*(typeof(clCreateEventFromEGLSyncKHR)*)p)(context, sync, display, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_event)0;
  }
}

CL_API_ENTRY cl_command_queue CL_API_CALL
clCreateCommandQueueWithProperties(cl_context                context ,
                                   cl_device_id              device ,
                                   const cl_queue_properties *     properties ,
                                   cl_int *                  errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateCommandQueueWithProperties");
  if(p) {
    return((*(typeof(clCreateCommandQueueWithProperties)*)p)(context, device, properties, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_command_queue)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreatePipe(cl_context                  context ,
             cl_mem_flags                flags ,
             cl_uint                     pipe_packet_size ,
             cl_uint                     pipe_max_packets ,
             const cl_pipe_properties *  properties ,
             cl_int *                    errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreatePipe");
  if(p) {
    return((*(typeof(clCreatePipe)*)p)(context, flags, pipe_packet_size, pipe_max_packets, properties, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetPipeInfo(cl_mem            pipe ,
              cl_pipe_info      param_name ,
              size_t            param_value_size ,
              void *            param_value ,
              size_t *          param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetPipeInfo");
  if(p) {
    return((*(typeof(clGetPipeInfo)*)p)(pipe, param_name, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY void * CL_API_CALL
clSVMAlloc(cl_context        context ,
           cl_svm_mem_flags  flags ,
           size_t            size ,
           cl_uint           alignment ){
  void (*p)()=dlsym(RTLD_NEXT, "clSVMAlloc");
  if(p) {
    return((*(typeof(clSVMAlloc)*)p)(context, flags, size, alignment));
  } else {
    printf("-1 : ");
    return (void *)0;
  }
}

CL_API_ENTRY void CL_API_CALL
clSVMFree(cl_context         context ,
          void *             svm_pointer ){
  void (*p)()=dlsym(RTLD_NEXT, "clSVMFree");
  if(p) {
    return((*(typeof(clSVMFree)*)p)(context, svm_pointer));
  } else {
    printf("-1 : ");
    return (void)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMFree(cl_command_queue   command_queue ,
                 cl_uint            num_svm_pointers ,
                 void *             svm_pointers[] ,
                 void (CL_CALLBACK * pfn_free_func)(cl_command_queue  queue ,
                                                        cl_uint           num_svm_pointers ,
                                                        void *            svm_pointers[] ,
                                                        void *            user_data ),
                 void *             user_data ,
                 cl_uint            num_events_in_wait_list ,
                 const cl_event *   event_wait_list ,
                 cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueSVMFree");
  if(p) {
    return((*(typeof(clEnqueueSVMFree)*)p)(command_queue, num_svm_pointers, svm_pointers, pfn_free_func, user_data, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMemcpy(cl_command_queue   command_queue ,
                   cl_bool            blocking_copy ,
                   void *             dst_ptr ,
                   const void *       src_ptr ,
                   size_t             size ,
                   cl_uint            num_events_in_wait_list ,
                   const cl_event *   event_wait_list ,
                   cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueSVMMemcpy");
  if(p) {
    return((*(typeof(clEnqueueSVMMemcpy)*)p)(command_queue, blocking_copy, dst_ptr, src_ptr, size, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMemFill(cl_command_queue   command_queue ,
                    void *             svm_ptr ,
                    const void *       pattern ,
                    size_t             pattern_size ,
                    size_t             size ,
                    cl_uint            num_events_in_wait_list ,
                    const cl_event *   event_wait_list ,
                    cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueSVMMemFill");
  if(p) {
    return((*(typeof(clEnqueueSVMMemFill)*)p)(command_queue, svm_ptr, pattern, pattern_size, size, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMap(cl_command_queue   command_queue ,
                cl_bool            blocking_map ,
                cl_map_flags       flags ,
                void *             svm_ptr ,
                size_t             size ,
                cl_uint            num_events_in_wait_list ,
                const cl_event *   event_wait_list ,
                cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueSVMMap");
  if(p) {
    return((*(typeof(clEnqueueSVMMap)*)p)(command_queue, blocking_map, flags, svm_ptr, size, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMUnmap(cl_command_queue   command_queue ,
                  void *             svm_ptr ,
                  cl_uint            num_events_in_wait_list ,
                  const cl_event *   event_wait_list ,
                  cl_event *         event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueSVMUnmap");
  if(p) {
    return((*(typeof(clEnqueueSVMUnmap)*)p)(command_queue, svm_ptr, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_sampler CL_API_CALL
clCreateSamplerWithProperties(cl_context                      context ,
                              const cl_sampler_properties *   normalized_coords ,
                              cl_int *                        errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateSamplerWithProperties");
  if(p) {
    return((*(typeof(clCreateSamplerWithProperties)*)p)(context, normalized_coords, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_sampler)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetKernelArgSVMPointer(cl_kernel     kernel ,
                         cl_uint       arg_index ,
                         const void *  arg_value ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetKernelArgSVMPointer");
  if(p) {
    return((*(typeof(clSetKernelArgSVMPointer)*)p)(kernel, arg_index, arg_value));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetKernelExecInfo(cl_kernel             kernel ,
                    cl_kernel_exec_info   param_name ,
                    size_t                param_value_size ,
                    const void *          param_value ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetKernelExecInfo");
  if(p) {
    return((*(typeof(clSetKernelExecInfo)*)p)(kernel, param_name, param_value_size, param_value));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetKernelSubGroupInfoKHR(cl_kernel  in_kernel ,
                           cl_device_id in_device,
                           cl_kernel_sub_group_info  param_name ,
                           size_t input_value_size,
                           const void * input_value,
                           size_t param_value_size,
                           void* param_value,
                           size_t* param_value_size_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetKernelSubGroupInfoKHR");
  if(p) {
    return((*(typeof(clGetKernelSubGroupInfoKHR)*)p)(in_kernel, in_device, param_name, input_value_size, input_value, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_kernel CL_API_CALL
clCloneKernel(cl_kernel      source_kernel ,
              cl_int*        errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCloneKernel");
  if(p) {
    return((*(typeof(clCloneKernel)*)p)(source_kernel, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_kernel)0;
  }
}

CL_API_ENTRY cl_program CL_API_CALL
clCreateProgramWithIL(cl_context     context ,
                      const void*     il ,
                      size_t          length ,
                      cl_int*         errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateProgramWithIL");
  if(p) {
    return((*(typeof(clCreateProgramWithIL)*)p)(context, il, length, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_program)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clEnqueueSVMMigrateMem(cl_command_queue          command_queue ,
                       cl_uint                   num_svm_pointers ,
                       const void **             svm_pointers ,
                       const size_t *            sizes ,
                       cl_mem_migration_flags    flags ,
                       cl_uint                   num_events_in_wait_list ,
                       const cl_event *          event_wait_list ,
                       cl_event *                event ){
  void (*p)()=dlsym(RTLD_NEXT, "clEnqueueSVMMigrateMem");
  if(p) {
    return((*(typeof(clEnqueueSVMMigrateMem)*)p)(command_queue, num_svm_pointers, svm_pointers, sizes, flags, num_events_in_wait_list, event_wait_list, event));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetDeviceAndHostTimer(cl_device_id     device ,
                        cl_ulong*        device_timestamp ,
                        cl_ulong*        host_timestamp ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetDeviceAndHostTimer");
  if(p) {
    return((*(typeof(clGetDeviceAndHostTimer)*)p)(device, device_timestamp, host_timestamp));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetHostTimer(cl_device_id  device ,
               cl_ulong *    host_timestamp ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetHostTimer");
  if(p) {
    return((*(typeof(clGetHostTimer)*)p)(device, host_timestamp));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clGetKernelSubGroupInfo(cl_kernel                    kernel ,
                        cl_device_id                 device ,
                        cl_kernel_sub_group_info     param_name ,
                        size_t                       input_value_size ,
                        const void*                  input_value ,
                        size_t                       param_value_size ,
                        void*                        param_value ,
                        size_t*                      param_value_size_ret  ){
  void (*p)()=dlsym(RTLD_NEXT, "clGetKernelSubGroupInfo");
  if(p) {
    return((*(typeof(clGetKernelSubGroupInfo)*)p)(kernel, device, param_name, input_value_size, input_value, param_value_size, param_value, param_value_size_ret));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetDefaultDeviceCommandQueue(cl_context            context ,
                               cl_device_id          device ,
                               cl_command_queue      command_queue ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetDefaultDeviceCommandQueue");
  if(p) {
    return((*(typeof(clSetDefaultDeviceCommandQueue)*)p)(context, device, command_queue));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetProgramReleaseCallback(cl_program           program ,
                            void (CL_CALLBACK *  pfn_notify )(cl_program  program , void *  user_data ),
                            void *               user_data ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetProgramReleaseCallback");
  if(p) {
    return((*(typeof(clSetProgramReleaseCallback)*)p)(program, pfn_notify, user_data));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetProgramSpecializationConstant(cl_program   program ,
                                   cl_uint      spec_id ,
                                   size_t       spec_size ,
                                   const void*  spec_value ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetProgramSpecializationConstant");
  if(p) {
    return((*(typeof(clSetProgramSpecializationConstant)*)p)(program, spec_id, spec_size, spec_value));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateBufferWithProperties(cl_context                 context ,
                             const cl_mem_properties *  properties ,
                             cl_mem_flags               flags ,
                             size_t                     size ,
                             void *                     host_ptr ,
                             cl_int *                   errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateBufferWithProperties");
  if(p) {
    return((*(typeof(clCreateBufferWithProperties)*)p)(context, properties, flags, size, host_ptr, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_mem CL_API_CALL
clCreateImageWithProperties(cl_context                 context ,
                            const cl_mem_properties *  properties ,
                            cl_mem_flags               flags ,
                            const cl_image_format *    image_format ,
                            const cl_image_desc *      image_desc ,
                            void *                     host_ptr ,
                            cl_int *                   errcode_ret ){
  void (*p)()=dlsym(RTLD_NEXT, "clCreateImageWithProperties");
  if(p) {
    return((*(typeof(clCreateImageWithProperties)*)p)(context, properties, flags, image_format, image_desc, host_ptr, errcode_ret));
  } else {
    printf("-1 : ");
    return (cl_mem)0;
  }
}

CL_API_ENTRY cl_int CL_API_CALL
clSetContextDestructorCallback(cl_context           context ,
                               void (CL_CALLBACK *  pfn_notify )(cl_context  context , void*  user_data ),
                               void *               user_data ){
  void (*p)()=dlsym(RTLD_NEXT, "clSetContextDestructorCallback");
  if(p) {
    return((*(typeof(clSetContextDestructorCallback)*)p)(context, pfn_notify, user_data));
  } else {
    printf("-1 : ");
    return (cl_int)0;
  }
}

